-- CodePath Academy — Accessibility (a11y) unit
-- Appends 5 more paid-tier Frontend lessons (a11y-why-it-matters through
-- a11y-final-project, sort_order 56-60, right after testing-final-project
-- at 55). Fourth item off the "not a full course yet" gap list. Unlike
-- Git/testing, no simulation is needed at all here — the sandbox already
-- runs real HTML/CSS, so every lesson is genuine, runnable accessible-
-- markup practice: semantic elements, alt text, real form labels, keyboard
-- focus styles, and a final project fixing a deliberately inaccessible
-- page. Safe to paste more than once — every insert is guarded with
-- "where not exists".
--
-- Generated by gen-a11y-lessons.js — don't hand-edit, regenerate instead.

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'a11y-why-it-matters',
  '{"en":"Why Accessibility Matters","de":"Warum Barrierefreiheit wichtig ist"}'::jsonb,
  '[{"step":1,"text":{"en":"Accessibility (often shortened to a11y) means building websites that people with disabilities can actually use — screen reader users, people who navigate by keyboard only, people with low vision, people with limited motor control.","de":"Barrierefreiheit (oft als a11y abgekürzt) bedeutet, Websites so zu bauen, dass Menschen mit Behinderungen sie tatsächlich nutzen können — Screenreader-Nutzer, Menschen, die nur mit der Tastatur navigieren, Menschen mit Sehschwäche, Menschen mit eingeschränkter motorischer Kontrolle."}},{"step":2,"text":{"en":"Run the starter code and look at the preview: the div and the button look identical. But try pressing Tab in a real browser — only the real button can receive keyboard focus and be activated with Enter or Space, for free, with zero extra code.","de":"Führe den Startcode aus und sieh dir die Vorschau an: der div und der button sehen identisch aus. Aber drücke in einem echten Browser Tab — nur der echte Button kann den Tastaturfokus erhalten und mit Enter oder Leertaste ausgelöst werden, kostenlos, ohne zusätzlichen Code."}},{"step":3,"text":{"en":"A screen reader also announces the button as \"Submit, button\" automatically. The div would just be silently read as text — a screen reader user would have no idea it does anything at all. This is the core idea behind the rest of this unit: use the right HTML element, and a lot of accessibility comes for free.","de":"Ein Screenreader kündigt den Button auch automatisch als \"Submit, Schaltfläche\" an. Der div würde nur stumm als Text vorgelesen — ein Screenreader-Nutzer hätte keine Ahnung, dass er überhaupt etwas tut. Das ist die Kernidee dieser ganzen Einheit: das richtige HTML-Element nutzen, dann kommt viel Barrierefreiheit gratis dazu."}}]'::jsonb,
  '{"html":"<!-- Both look like buttons. Only one actually behaves like one. -->\n<div class=\"button-like\">Submit</div>\n<button>Submit</button>\n","css":".button-like, button {\n  background: #34d399;\n  color: white;\n  border: none;\n  padding: 10px 16px;\n  font-size: 14px;\n  border-radius: 8px;\n  cursor: pointer;\n  display: block;\n  margin-bottom: 8px;\n}\n"}'::jsonb,
  'beginner', false, false,
  56
where not exists (select 1 from lessons where slug = 'a11y-why-it-matters');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'a11y-why-it-matters'),
  '{"en":"Why is a real `<button>` better than a `<div>` styled to look like one?","de":"Warum ist ein echter `<button>` besser als ein `<div>`, das wie einer aussieht?"}'::jsonb,
  '{"en":["Buttons render faster","A real button is automatically keyboard-focusable and announced correctly by screen readers","Divs cannot have a background color","There''s no real difference"],"de":["Buttons rendern schneller","Ein echter Button ist automatisch mit der Tastatur fokussierbar und wird von Screenreadern korrekt angekündigt","Divs können keine Hintergrundfarbe haben","Es gibt keinen echten Unterschied"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'a11y-why-it-matters')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'a11y-semantic-html',
  '{"en":"Semantic HTML","de":"Semantisches HTML"}'::jsonb,
  '[{"step":1,"text":{"en":"Tags like header, nav, main, and footer describe what a section of the page actually IS, not just how it looks — this is called semantic HTML, and it''s the foundation everything else in this unit builds on.","de":"Tags wie header, nav, main und footer beschreiben, was ein Abschnitt der Seite tatsächlich IST, nicht nur wie er aussieht — das nennt man semantisches HTML, und es ist die Grundlage, auf der der Rest dieser Einheit aufbaut."}},{"step":2,"text":{"en":"A screen reader user can jump directly to <main> or to the <nav> using keyboard shortcuts, skipping repeated header content — but only if you actually used these tags instead of generic <div>s for everything.","de":"Ein Screenreader-Nutzer kann mit Tastenkürzeln direkt zu <main> oder zu <nav> springen und wiederholten Header-Inhalt überspringen — aber nur, wenn du diese Tags tatsächlich verwendet hast, statt für alles generische <div>s."}},{"step":3,"text":{"en":"A useful rule: reach for a semantic tag (header, nav, main, article, footer, button) whenever one exists for what you''re building, and only fall back to a plain <div> when none of them fit.","de":"Eine nützliche Regel: Greife zu einem semantischen Tag (header, nav, main, article, footer, button), wann immer eines für das passt, was du baust, und nutze ein einfaches <div> nur, wenn keines davon passt."}}]'::jsonb,
  '{"html":"<header>\n  <h1>My Blog</h1>\n  <nav>\n    <a href=\"#\">Home</a>\n    <a href=\"#\">Articles</a>\n  </nav>\n</header>\n\n<main>\n  <h2>Latest Post</h2>\n  <p>Semantic HTML describes the meaning of content, not just its look.</p>\n</main>\n\n<footer>\n  <p>&copy; 2026 My Blog</p>\n</footer>\n","css":"header, main, footer { padding: 16px; }\nnav a { margin-right: 12px; }\n"}'::jsonb,
  'beginner', false, false,
  57
where not exists (select 1 from lessons where slug = 'a11y-semantic-html');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'a11y-semantic-html'),
  '{"en":"What does semantic HTML describe?","de":"Was beschreibt semantisches HTML?"}'::jsonb,
  '{"en":["The color scheme of a page","What a piece of content actually is/means, not just its visual style","How fast a page loads","The programming language used"],"de":["Das Farbschema einer Seite","Was ein Inhalt tatsächlich ist/bedeutet, nicht nur sein visueller Stil","Wie schnell eine Seite lädt","Die verwendete Programmiersprache"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'a11y-semantic-html')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'a11y-alt-text-and-labels',
  '{"en":"Alt Text and Form Labels","de":"Alt-Texte und Formular-Labels"}'::jsonb,
  '[{"step":1,"text":{"en":"Every meaningful <img> needs an alt attribute — a short text description of what the image shows, read aloud by screen readers since they can''t see the picture itself.","de":"Jedes bedeutungsvolle <img> braucht ein alt-Attribut — eine kurze Textbeschreibung dessen, was das Bild zeigt, die von Screenreadern vorgelesen wird, da sie das Bild selbst nicht sehen können."}},{"step":2,"text":{"en":"A placeholder is NOT a label — it disappears the moment you start typing, and many screen readers don''t reliably announce it at all. A real <label for=\"...\"> connected to the input''s id is what actually works.","de":"Ein Placeholder ist KEIN Label — er verschwindet, sobald du zu tippen beginnst, und viele Screenreader kündigen ihn nicht zuverlässig an. Ein echtes <label for=\"...\">, das mit der id des Inputs verbunden ist, funktioniert tatsächlich."}},{"step":3,"text":{"en":"Fix the starter code: add alt=\"...\" describing the image, and wrap the input with a proper <label for=\"email\"> connected via a matching id=\"email\" on the input.","de":"Korrigiere den Startcode: Füge alt=\"...\" mit einer Beschreibung des Bildes hinzu und verbinde den Input mit einem echten <label for=\"email\"> über eine passende id=\"email\" am Input."}}]'::jsonb,
  '{"html":"<!-- This image has no description for someone who can''t see it. -->\n<img src=\"https://placehold.co/200x100\" />\n\n<!-- This input has no label connecting it to its purpose. -->\n<input type=\"email\" placeholder=\"Email\" />\n\n<!-- Fix both above: add an alt attribute, and a real <label>. -->\n","css":""}'::jsonb,
  'beginner', false, false,
  58
where not exists (select 1 from lessons where slug = 'a11y-alt-text-and-labels');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'a11y-alt-text-and-labels'),
  '{"en":"Why isn''t a placeholder attribute a substitute for a real `<label>`?","de":"Warum ist ein placeholder-Attribut kein Ersatz für ein echtes `<label>`?"}'::jsonb,
  '{"en":["Placeholders are only for numbers","It disappears once typing starts and isn''t reliably announced by screen readers","Placeholders make the page slower","There''s no difference at all"],"de":["Placeholder sind nur für Zahlen","Er verschwindet, sobald man tippt, und wird von Screenreadern nicht zuverlässig angekündigt","Placeholder machen die Seite langsamer","Es gibt überhaupt keinen Unterschied"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'a11y-alt-text-and-labels')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'a11y-keyboard-navigation',
  '{"en":"Keyboard Navigation & Focus","de":"Tastaturnavigation & Fokus"}'::jsonb,
  '[{"step":1,"text":{"en":"Many people never use a mouse at all — they Tab between links and buttons, and press Enter or Space to activate whichever one currently has focus.","de":"Viele Menschen nutzen überhaupt keine Maus — sie tabben zwischen Links und Buttons und drücken Enter oder Leertaste, um das gerade fokussierte Element zu aktivieren."}},{"step":2,"text":{"en":":focus-visible lets you style what a keyboard-focused element looks like — a clear outline, like the one in the starter CSS. Removing this with outline: none and nothing to replace it is one of the most common real accessibility bugs.","de":":focus-visible lässt dich gestalten, wie ein per Tastatur fokussiertes Element aussieht — ein klarer Rahmen, wie im Start-CSS. Ihn mit outline: none zu entfernen, ohne Ersatz, ist einer der häufigsten echten Barrierefreiheits-Bugs."}},{"step":3,"text":{"en":"The .fake-clickable div at the bottom can never receive keyboard focus at all — Tab just skips right over it, no matter how clickable it looks. This is the same lesson from earlier in the unit, now seen from the keyboard''s point of view.","de":"Das .fake-clickable-div unten kann niemals den Tastaturfokus erhalten — Tab überspringt es einfach, egal wie klickbar es aussieht. Das ist dieselbe Lektion wie zu Beginn dieser Einheit, jetzt aus der Sicht der Tastatur betrachtet."}}]'::jsonb,
  '{"html":"<a href=\"#\">Link one</a>\n<a href=\"#\">Link two</a>\n<button>A button</button>\n<div class=\"fake-clickable\">Looks clickable, but isn''t keyboard-reachable</div>\n","css":"a, button { display: block; margin: 8px 0; width: fit-content; }\n\n/* Try it: comment this rule out and press Tab in a real browser —\n   notice you completely lose track of where your keyboard focus is. */\na:focus-visible, button:focus-visible {\n  outline: 3px solid #38bdf8;\n  outline-offset: 2px;\n}\n\n.fake-clickable {\n  color: #949eb8;\n  font-style: italic;\n}\n"}'::jsonb,
  'intermediate', false, false,
  59
where not exists (select 1 from lessons where slug = 'a11y-keyboard-navigation');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'a11y-keyboard-navigation'),
  '{"en":"What''s the risk of writing `outline: none` on a focusable element without adding a replacement style?","de":"Was ist das Risiko, bei einem fokussierbaren Element `outline: none` zu setzen, ohne einen Ersatz-Stil hinzuzufügen?"}'::jsonb,
  '{"en":["The page loads slower","Keyboard users lose all visual indication of where their focus is","The element stops being clickable with a mouse","Nothing, it''s purely cosmetic"],"de":["Die Seite lädt langsamer","Tastaturnutzer verlieren jede visuelle Anzeige, wo sich ihr Fokus befindet","Das Element ist mit der Maus nicht mehr klickbar","Nichts, es ist rein kosmetisch"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'a11y-keyboard-navigation')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'a11y-final-project',
  '{"en":"Project: Fix an Inaccessible Page","de":"Projekt: Eine unzugängliche Seite reparieren"}'::jsonb,
  '[{"step":1,"text":{"en":"Final project: combine everything from this unit — semantic elements, real labels, alt text, and keyboard focus — to fix a page full of accessibility problems.","de":"Abschlussprojekt: Kombiniere alles aus dieser Einheit — semantische Elemente, echte Labels, Alt-Texte und Tastaturfokus — um eine Seite voller Barrierefreiheits-Probleme zu reparieren."}},{"step":2,"text":{"en":"One new tool for icon-only buttons: aria-label=\"Close\" gives an element an accessible name even when there''s no visible text — essential for the ✕ button here, which has nothing a screen reader could otherwise announce.","de":"Ein neues Werkzeug für Icon-only-Buttons: aria-label=\"Close\" gibt einem Element einen zugänglichen Namen, auch wenn kein sichtbarer Text da ist — essenziell für den ✕-Button hier, der sonst nichts hätte, was ein Screenreader ankündigen könnte."}},{"step":3,"text":{"en":"Rewrite the file: <nav> with real links or buttons instead of the .nav divs, a proper heading tag for \"Contact Us\", a <label> for the name input, alt text on the image, and aria-label on the icon button — then submit it to your portfolio.","de":"Schreibe die Datei um: <nav> mit echten Links oder Buttons statt der .nav-divs, ein echtes Überschriften-Tag für \"Contact Us\", ein <label> für den Namens-Input, Alt-Text beim Bild und aria-label beim Icon-Button — reiche es dann in dein Portfolio ein."}}]'::jsonb,
  '{"html":"<div class=\"nav\">\n  <div>Home</div>\n  <div>About</div>\n</div>\n\n<div class=\"title\">Contact Us</div>\n\n<input placeholder=\"Your name\" />\n\n<div class=\"icon-btn\">✕</div>\n\n<img src=\"https://placehold.co/150x80\" />\n\n<!-- Your task: fix every accessibility problem in this file.\n     Hints: real nav/button/label elements, alt text, and an\n     aria-label on the icon-only close button (it has no visible\n     text, so aria-label is the only way to give it an accessible name). -->\n","css":".nav div, .icon-btn { cursor: pointer; }\n.title { font-size: 22px; font-weight: bold; }\n"}'::jsonb,
  'advanced', false, true,
  60
where not exists (select 1 from lessons where slug = 'a11y-final-project');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'a11y-final-project'),
  '{"en":"Why does the ✕ icon-only close button need `aria-label=\"Close\"`?","de":"Warum braucht der Icon-only-Schließen-Button (✕) `aria-label=\"Close\"`?"}'::jsonb,
  '{"en":["It doesn''t, icons are always accessible on their own","It has no visible text, so aria-label gives screen readers something to announce","aria-label changes the button''s color","It''s only needed on mobile devices"],"de":["Braucht er nicht, Icons sind von selbst immer barrierefrei","Es gibt keinen sichtbaren Text, aria-label gibt Screenreadern etwas zum Ankündigen","aria-label ändert die Farbe des Buttons","Nur auf Mobilgeräten nötig"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'a11y-final-project')
);

