-- CodePath Academy — deeper Backend lessons
-- Appends 6 more paid-tier Backend lessons (Express middleware, SQL basics,
-- SQL joins, REST API design, a Supabase concept lesson, and a full-stack
-- capstone project) right after backend-paid-exam (sort_order 16). Run this
-- in the Supabase SQL editor after checkpoint_exams.sql. Safe to paste more
-- than once — every insert is guarded with "where not exists".
--
-- Generated by gen-backend-deep-lessons.js — don't hand-edit, regenerate instead.

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-express-middleware',
  '{"en":"Express: Middleware","de":"Express: Middleware"}'::jsonb,
  '[{"step":1,"text":{"en":"Express handles requests through a chain of functions called middleware — each one can inspect or modify the request before passing it along, or stop it entirely.","de":"Express verarbeitet Anfragen durch eine Kette von Funktionen namens Middleware — jede kann die Anfrage prüfen oder verändern, bevor sie weitergereicht wird, oder sie ganz stoppen."}},{"step":2,"text":{"en":"A common use is an auth-guard: middleware that checks if a user is logged in before letting the request continue to the real route handler.","de":"Ein häufiger Einsatz ist ein Auth-Guard: Middleware, die prüft, ob ein Nutzer angemeldet ist, bevor die Anfrage zum eigentlichen Route-Handler weitergeht."}},{"step":3,"text":{"en":"Write a simulated requireAuth(request) middleware that returns an error if request.user is missing, otherwise lets the request through.","de":"Schreibe eine simulierte requireAuth(request)-Middleware, die einen Fehler zurückgibt, wenn request.user fehlt, und die Anfrage sonst durchlässt."}}]'::jsonb,
  '{"js":"function requireAuth(request, next) {\n  if (!request.user) {\n    return { status: 401, body: \"Unauthorized\" };\n  }\n  return next(request);\n}\n\nfunction homeRoute(request) {\n  return { status: 200, body: \"Welcome, \" + request.user };\n}\n\nconsole.log(requireAuth({ user: \"Ahmed\" }, homeRoute));\nconsole.log(requireAuth({}, homeRoute));"}'::jsonb,
  'intermediate', false, false,
  17
where not exists (select 1 from lessons where slug = 'backend-express-middleware');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-express-middleware'),
  '{"en":"What is middleware in Express used for?","de":"Wofür wird Middleware in Express genutzt?"}'::jsonb,
  '{"en":["Styling the frontend","Running code between a request arriving and the route handler responding","Storing files on disk","Compiling JavaScript"],"de":["Um das Frontend zu stylen","Um Code zwischen dem Eintreffen einer Anfrage und der Antwort des Route-Handlers auszuführen","Um Dateien auf der Festplatte zu speichern","Um JavaScript zu kompilieren"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-express-middleware')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-sql-basics',
  '{"en":"SQL: Querying a Database","de":"SQL: Eine Datenbank abfragen"}'::jsonb,
  '[{"step":1,"text":{"en":"SQL (Structured Query Language) is how you ask a database for data. SELECT chooses which columns, FROM chooses the table, and WHERE filters the rows.","de":"SQL (Structured Query Language) ist die Art, wie du eine Datenbank nach Daten fragst. SELECT wählt die Spalten, FROM die Tabelle, und WHERE filtert die Zeilen."}},{"step":2,"text":{"en":"This simulated query() function mimics running SQL against a table of users stored as a plain array — real SQL does the exact same filtering, just against real disk storage.","de":"Diese simulierte query()-Funktion ahmt eine SQL-Abfrage gegen eine users-Tabelle nach, die als einfaches Array gespeichert ist — echtes SQL macht genau dasselbe Filtern, nur gegen echten Speicher."}},{"step":3,"text":{"en":"Change the WHERE condition to find only users older than 20.","de":"Ändere die WHERE-Bedingung, sodass nur Nutzer über 20 gefunden werden."}}]'::jsonb,
  '{"js":"const users = [\n  { name: \"Ahmed\", age: 19 },\n  { name: \"Lina\", age: 22 },\n  { name: \"Sam\", age: 17 },\n];\n\n// Simulates: SELECT name FROM users WHERE age > 18\nfunction query(table, whereFn) {\n  return table.filter(whereFn).map((row) => row.name);\n}\n\nconsole.log(query(users, (user) => user.age > 18));"}'::jsonb,
  'intermediate', false, false,
  18
where not exists (select 1 from lessons where slug = 'backend-sql-basics');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-sql-basics'),
  '{"en":"In SQL, what does the WHERE clause do?","de":"Was macht die WHERE-Klausel in SQL?"}'::jsonb,
  '{"en":["Chooses which table to use","Filters rows based on a condition","Deletes the table","Sorts columns alphabetically"],"de":["Wählt die zu nutzende Tabelle","Filtert Zeilen anhand einer Bedingung","Löscht die Tabelle","Sortiert Spalten alphabetisch"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-sql-basics')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-sql-joins',
  '{"en":"SQL: Joining Tables","de":"SQL: Tabellen verbinden"}'::jsonb,
  '[{"step":1,"text":{"en":"Real data is split across multiple tables — users in one table, their orders in another. A JOIN combines rows from both tables that share a matching id.","de":"Echte Daten sind über mehrere Tabellen verteilt — Nutzer in einer Tabelle, ihre Bestellungen in einer anderen. Ein JOIN verbindet Zeilen aus beiden Tabellen, die eine übereinstimmende id haben."}},{"step":2,"text":{"en":"This simulated join connects each order to its user by matching userId to a user''s id — the same idea as a real SQL JOIN ... ON.","de":"Dieser simulierte Join verbindet jede Bestellung mit ihrem Nutzer, indem userId mit der id eines Nutzers abgeglichen wird — dieselbe Idee wie ein echtes SQL JOIN ... ON."}},{"step":3,"text":{"en":"Run it to see each order paired with the name of the user who placed it.","de":"Führe es aus, um jede Bestellung mit dem Namen des Nutzers zu sehen, der sie aufgegeben hat."}}]'::jsonb,
  '{"js":"const users = [\n  { id: 1, name: \"Ahmed\" },\n  { id: 2, name: \"Lina\" },\n];\n\nconst orders = [\n  { id: 101, userId: 1, item: \"Keyboard\" },\n  { id: 102, userId: 2, item: \"Monitor\" },\n];\n\n// Simulates: SELECT orders.item, users.name FROM orders JOIN users ON orders.userId = users.id\nfunction joinOrdersWithUsers() {\n  return orders.map((order) => {\n    const user = users.find((u) => u.id === order.userId);\n    return { item: order.item, boughtBy: user.name };\n  });\n}\n\nconsole.log(joinOrdersWithUsers());"}'::jsonb,
  'intermediate', false, false,
  19
where not exists (select 1 from lessons where slug = 'backend-sql-joins');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-sql-joins'),
  '{"en":"What does a JOIN let you do in SQL?","de":"Was ermöglicht dir ein JOIN in SQL?"}'::jsonb,
  '{"en":["Delete rows from two tables at once","Combine related rows from two different tables","Create a new database","Style query results"],"de":["Zeilen aus zwei Tabellen gleichzeitig löschen","Zusammengehörige Zeilen aus zwei verschiedenen Tabellen verbinden","Eine neue Datenbank erstellen","Abfrageergebnisse stylen"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-sql-joins')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-rest-api-design',
  '{"en":"Designing a REST API","de":"Eine REST-API entwerfen"}'::jsonb,
  '[{"step":1,"text":{"en":"REST APIs use HTTP methods to mean different actions on the same URL: GET reads, POST creates, PUT updates, DELETE removes.","de":"REST-APIs nutzen HTTP-Methoden, um unterschiedliche Aktionen an derselben URL zu bedeuten: GET liest, POST erstellt, PUT aktualisiert, DELETE entfernt."}},{"step":2,"text":{"en":"Status codes tell the client what happened: 200 OK, 201 Created, 404 Not Found, 401 Unauthorized.","de":"Statuscodes sagen dem Client, was passiert ist: 200 OK, 201 Created, 404 Not Found, 401 Unauthorized."}},{"step":3,"text":{"en":"Write a simulated handleRequest(method, path) for a /tasks endpoint that responds correctly to GET and POST.","de":"Schreibe ein simuliertes handleRequest(method, path) für einen /tasks-Endpunkt, das korrekt auf GET und POST reagiert."}}]'::jsonb,
  '{"js":"function handleRequest(method, path) {\n  if (path === \"/tasks\" && method === \"GET\") {\n    return { status: 200, body: [\"Buy milk\", \"Learn REST\"] };\n  }\n  if (path === \"/tasks\" && method === \"POST\") {\n    return { status: 201, body: \"Task created\" };\n  }\n  return { status: 404, body: \"Not found\" };\n}\n\nconsole.log(handleRequest(\"GET\", \"/tasks\"));\nconsole.log(handleRequest(\"POST\", \"/tasks\"));\nconsole.log(handleRequest(\"DELETE\", \"/tasks\"));"}'::jsonb,
  'intermediate', false, false,
  20
where not exists (select 1 from lessons where slug = 'backend-rest-api-design');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-rest-api-design'),
  '{"en":"Which HTTP method is conventionally used to create a new resource in a REST API?","de":"Welche HTTP-Methode wird üblicherweise genutzt, um eine neue Ressource in einer REST-API zu erstellen?"}'::jsonb,
  '{"en":["GET","POST","DELETE","HEAD"],"de":["GET","POST","DELETE","HEAD"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-rest-api-design')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-supabase-intro',
  '{"en":"Supabase: A Real Backend, Free","de":"Supabase: Ein echtes Backend, kostenlos"}'::jsonb,
  '[{"step":1,"text":{"en":"Everything you''ve simulated — a server, routes, a database, authentication — is exactly what Supabase gives you for real, for free, without managing your own server.","de":"Alles, was du simuliert hast — ein Server, Routen, eine Datenbank, Authentifizierung — ist genau das, was dir Supabase wirklich gibt, kostenlos, ohne einen eigenen Server zu verwalten."}},{"step":2,"text":{"en":"Supabase runs a real PostgreSQL database plus a real auth system, and gives your frontend a JavaScript client to talk to both — this whole platform is actually built on it.","de":"Supabase betreibt eine echte PostgreSQL-Datenbank plus ein echtes Auth-System und gibt deinem Frontend einen JavaScript-Client, um mit beidem zu sprechen — genau darauf ist diese ganze Plattform aufgebaut."}},{"step":3,"text":{"en":"You won''t run real Supabase code inside these lessons, but everything you''ve learned — tables, SQL, auth, sessions — maps directly onto how it works.","de":"Du wirst in diesen Lektionen keinen echten Supabase-Code ausführen, aber alles, was du gelernt hast — Tabellen, SQL, Auth, Sessions — überträgt sich direkt darauf, wie es funktioniert."}}]'::jsonb,
  null,
  'beginner', false, false,
  21
where not exists (select 1 from lessons where slug = 'backend-supabase-intro');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-supabase-intro'),
  '{"en":"What does Supabase provide, based on what you''ve already learned?","de":"Was bietet Supabase, basierend auf dem, was du bereits gelernt hast?"}'::jsonb,
  '{"en":["A real PostgreSQL database and a real auth system","Only a code editor","A way to style websites","A video hosting service"],"de":["Eine echte PostgreSQL-Datenbank und ein echtes Auth-System","Nur einen Code-Editor","Eine Möglichkeit, Websites zu stylen","Einen Video-Hosting-Dienst"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-supabase-intro')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-fullstack-capstone',
  '{"en":"Project: Full-Stack Task Board","de":"Projekt: Full-Stack Aufgabenboard"}'::jsonb,
  '[{"step":1,"text":{"en":"Time to put frontend and backend together the way a real full-stack app works: a UI that calls an API, and an API that talks to a simulated database.","de":"Zeit, Frontend und Backend so zusammenzubringen, wie eine echte Full-Stack-App funktioniert: eine Oberfläche, die eine API aufruft, und eine API, die mit einer simulierten Datenbank spricht."}},{"step":2,"text":{"en":"Build a simulated API (getTasks, addTask) backed by an in-memory array, then a simulated fetch layer that calls it — the same shape as a real frontend calling a real backend.","de":"Baue eine simulierte API (getTasks, addTask), die von einem Array im Speicher unterstützt wird, dann eine simulierte Fetch-Schicht, die sie aufruft — genau wie ein echtes Frontend, das ein echtes Backend aufruft."}},{"step":3,"text":{"en":"This is the same pattern you''ll use with React + a real Express + Supabase backend later — only the network calls are simulated here.","de":"Das ist dasselbe Muster, das du später mit React + einem echten Express + Supabase-Backend nutzt — nur die Netzwerkaufrufe sind hier simuliert."}}]'::jsonb,
  '{"js":"// Simulated database\nlet tasks = [{ id: 1, title: \"Learn full-stack basics\" }];\n\n// Simulated backend API\nfunction api(method, path, body) {\n  if (method === \"GET\" && path === \"/tasks\") {\n    return { status: 200, body: tasks };\n  }\n  if (method === \"POST\" && path === \"/tasks\") {\n    const newTask = { id: tasks.length + 1, title: body.title };\n    tasks.push(newTask);\n    return { status: 201, body: newTask };\n  }\n  return { status: 404, body: \"Not found\" };\n}\n\n// Simulated frontend calling the API\nfunction loadTasks() {\n  return api(\"GET\", \"/tasks\").body;\n}\n\nfunction createTask(title) {\n  return api(\"POST\", \"/tasks\", { title }).body;\n}\n\nconsole.log(loadTasks());\nconsole.log(createTask(\"Build a full-stack project\"));\nconsole.log(loadTasks());"}'::jsonb,
  'advanced', false, true,
  22
where not exists (select 1 from lessons where slug = 'backend-fullstack-capstone');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-fullstack-capstone'),
  '{"en":"In this exercise, what plays the role of a real database?","de":"Was übernimmt in dieser Übung die Rolle einer echten Datenbank?"}'::jsonb,
  '{"en":["The tasks array kept in memory","The console.log statements","The api() function''s method parameter","The HTML page"],"de":["Das tasks-Array, das im Speicher gehalten wird","Die console.log-Anweisungen","Der method-Parameter der api()-Funktion","Die HTML-Seite"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-fullstack-capstone')
);

