-- CodePath Academy — checkpoint exams
-- Adds a mid-part "checkpoint" exam to each curriculum part that previously
-- only had an end-of-part exam (HTML/CSS, JavaScript, Backend foundations,
-- Backend security). Run this in the Supabase SQL editor AFTER schema.sql
-- and seed.sql have already been run once.
--
-- Every step below is guarded ("if not exists" / "where not exists"), so
-- it is safe to paste and run this file more than once.
--
-- Generated by gen-checkpoint-exams.js — don't hand-edit, regenerate instead.

-- Shift lessons at/after position 9 in "frontend" to make room for "html-css-checkpoint-exam"
do $$
begin
  if not exists (select 1 from lessons where slug = 'html-css-checkpoint-exam') then
    update lessons
      set sort_order = sort_order + 1
      where course_id = (select id from courses where slug = 'frontend')
        and sort_order >= 9;
  end if;
end $$;

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'html-css-checkpoint-exam',
  '{"en":"Checkpoint: HTML & CSS","de":"Zwischenprüfung: HTML & CSS"}'::jsonb,
  '[{"step":1,"text":{"en":"This is a checkpoint — a short exam that checks everything you''ve built so far: structure, styling, layout, and semantic HTML.","de":"Das ist eine Zwischenprüfung — ein kurzer Test für alles, was du bisher gebaut hast: Struktur, Styling, Layout und semantisches HTML."}},{"step":2,"text":{"en":"Extend your profile card into a small \"About Me\" section using flexbox for layout, real HTML5 semantic tags (header, main, section), and the box-model spacing you just learned.","de":"Erweitere deine Profilkarte zu einem kleinen „Über mich\"-Bereich — mit Flexbox fürs Layout, echten semantischen HTML5-Tags (header, main, section) und den Box-Model-Abständen, die du gerade gelernt hast."}},{"step":3,"text":{"en":"Press Run to preview, then submit your project below when you''re done — same flow as a real assignment.","de":"Klicke auf Ausführen für die Vorschau und reiche dein Projekt unten ein, wenn du fertig bist — genau wie bei einer echten Aufgabe."}}]'::jsonb,
  '{"html":"<header>\n  <h1>Ahmed</h1>\n</header>\n<main>\n  <section class=\"about\">\n    <p>Add a short paragraph about yourself here.</p>\n  </section>\n</main>","css":"body {\n  font-family: sans-serif;\n}\n\n.about {\n  display: flex;\n  flex-direction: column;\n  padding: 16px;\n  border: 1px solid #ccc;\n}"}'::jsonb,
  'intermediate', true, true,
  9
where not exists (select 1 from lessons where slug = 'html-css-checkpoint-exam');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'html-css-checkpoint-exam'),
  '{"en":"Which HTML5 element is the correct semantic choice for a page''s main navigation links?","de":"Welches HTML5-Element ist die richtige semantische Wahl für die Hauptnavigation einer Seite?"}'::jsonb,
  '{"en":["<div>","<nav>","<span>","<p>"],"de":["<div>","<nav>","<span>","<p>"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'html-css-checkpoint-exam')
);

-- Shift lessons at/after position 23 in "frontend" to make room for "js-checkpoint-exam"
do $$
begin
  if not exists (select 1 from lessons where slug = 'js-checkpoint-exam') then
    update lessons
      set sort_order = sort_order + 1
      where course_id = (select id from courses where slug = 'frontend')
        and sort_order >= 23;
  end if;
end $$;

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'js-checkpoint-exam',
  '{"en":"Checkpoint: JavaScript Fundamentals","de":"Zwischenprüfung: JavaScript-Grundlagen"}'::jsonb,
  '[{"step":1,"text":{"en":"You''ve learned variables, conditions, loops, and functions — the core building blocks of any program.","de":"Du hast Variablen, Bedingungen, Schleifen und Funktionen gelernt — die Grundbausteine jedes Programms."}},{"step":2,"text":{"en":"Write a function that takes a number and returns whether it''s even or odd, then loop from 1 to 10 and log the result for each number.","de":"Schreibe eine Funktion, die eine Zahl entgegennimmt und zurückgibt, ob sie gerade oder ungerade ist. Durchlaufe dann 1 bis 10 und logge das Ergebnis für jede Zahl."}},{"step":3,"text":{"en":"This checkpoint only uses what you''ve learned so far — no arrays or objects yet, those come right after this.","de":"Diese Zwischenprüfung nutzt nur das, was du bisher gelernt hast — noch keine Arrays oder Objekte, die kommen direkt danach."}}]'::jsonb,
  '{"js":"function evenOrOdd(number) {\n  // return \"even\" or \"odd\"\n}\n\nfor (let i = 1; i <= 10; i++) {\n  console.log(i, evenOrOdd(i));\n}"}'::jsonb,
  'intermediate', false, true,
  23
where not exists (select 1 from lessons where slug = 'js-checkpoint-exam');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'js-checkpoint-exam'),
  '{"en":"What does the % operator do in JavaScript?","de":"Was macht der %-Operator in JavaScript?"}'::jsonb,
  '{"en":["Divides two numbers","Returns the remainder of a division","Multiplies two numbers","Rounds a number"],"de":["Dividiert zwei Zahlen","Gibt den Rest einer Division zurück","Multipliziert zwei Zahlen","Rundet eine Zahl"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'js-checkpoint-exam')
);

-- Shift lessons at/after position 5 in "backend" to make room for "backend-foundations-checkpoint-exam"
do $$
begin
  if not exists (select 1 from lessons where slug = 'backend-foundations-checkpoint-exam') then
    update lessons
      set sort_order = sort_order + 1
      where course_id = (select id from courses where slug = 'backend')
        and sort_order >= 5;
  end if;
end $$;

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-foundations-checkpoint-exam',
  '{"en":"Checkpoint: How the Web Works","de":"Zwischenprüfung: Wie das Web funktioniert"}'::jsonb,
  '[{"step":1,"text":{"en":"Before Express and databases, let''s make sure the fundamentals are solid: what a server is, how requests and responses work, and what Node.js actually is.","de":"Bevor es mit Express und Datenbanken weitergeht, sollten die Grundlagen sitzen: was ein Server ist, wie Anfragen und Antworten funktionieren, und was Node.js eigentlich ist."}},{"step":2,"text":{"en":"Using the same simulated request-handling style from earlier lessons, write a function that returns a different response for the \"/home\" path than for any other path.","de":"Schreibe im gleichen simulierten Stil wie in den vorherigen Lektionen eine Funktion, die für den Pfad „/home\" eine andere Antwort liefert als für jeden anderen Pfad."}},{"step":3,"text":{"en":"This checkpoint uses plain simulated JavaScript, just like the lessons before it — real Express comes right after this.","de":"Diese Zwischenprüfung nutzt einfaches, simuliertes JavaScript, genau wie die Lektionen davor — echtes Express kommt direkt danach."}}]'::jsonb,
  '{"js":"function handleRequest(path) {\n  // return \"Welcome home!\" for \"/home\", otherwise \"Not found\"\n}\n\nconsole.log(handleRequest(\"/home\"));\nconsole.log(handleRequest(\"/about\"));"}'::jsonb,
  'intermediate', true, true,
  5
where not exists (select 1 from lessons where slug = 'backend-foundations-checkpoint-exam');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-foundations-checkpoint-exam'),
  '{"en":"What is the job of a server?","de":"Was ist die Aufgabe eines Servers?"}'::jsonb,
  '{"en":["To render CSS in the browser","To store your keyboard shortcuts","To respond to requests from a browser with data or files","To compile JavaScript into HTML"],"de":["CSS im Browser darzustellen","Tastenkürzel zu speichern","Anfragen eines Browsers mit Daten oder Dateien zu beantworten","JavaScript zu HTML zu kompilieren"]}'::jsonb,
  2,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-foundations-checkpoint-exam')
);

-- Shift lessons at/after position 12 in "backend" to make room for "backend-security-checkpoint-exam"
do $$
begin
  if not exists (select 1 from lessons where slug = 'backend-security-checkpoint-exam') then
    update lessons
      set sort_order = sort_order + 1
      where course_id = (select id from courses where slug = 'backend')
        and sort_order >= 12;
  end if;
end $$;

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-security-checkpoint-exam',
  '{"en":"Checkpoint: Data & Password Security","de":"Zwischenprüfung: Daten & Passwortsicherheit"}'::jsonb,
  '[{"step":1,"text":{"en":"You now know how data is organized in database tables, and why passwords must never be stored in plain text.","de":"Du weißt jetzt, wie Daten in Datenbanktabellen organisiert werden — und warum Passwörter niemals im Klartext gespeichert werden dürfen."}},{"step":2,"text":{"en":"Write a simulated hashPassword(password) function (a simplified stand-in for real hashing) and an isStrongPassword(password) check that requires at least 8 characters.","de":"Schreibe eine simulierte Funktion hashPassword(password) (ein vereinfachter Platzhalter für echtes Hashing) und eine Prüfung isStrongPassword(password), die mindestens 8 Zeichen verlangt."}},{"step":3,"text":{"en":"Real registration flows, sessions, and authentication come next — this checkpoint makes sure the fundamentals are locked in first.","de":"Echte Registrierungsabläufe, Sessions und Authentifizierung kommen als Nächstes — diese Zwischenprüfung stellt sicher, dass die Grundlagen sitzen."}}]'::jsonb,
  '{"js":"function hashPassword(password) {\n  // return a simplified \"hashed\" version of the password\n}\n\nfunction isStrongPassword(password) {\n  // return true if password.length >= 8\n}\n\nconsole.log(hashPassword(\"hunter2\"));\nconsole.log(isStrongPassword(\"hunter2\"));"}'::jsonb,
  'intermediate', false, true,
  12
where not exists (select 1 from lessons where slug = 'backend-security-checkpoint-exam');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-security-checkpoint-exam'),
  '{"en":"Why should passwords never be stored as plain text in a database?","de":"Warum sollten Passwörter niemals im Klartext in einer Datenbank gespeichert werden?"}'::jsonb,
  '{"en":["It takes up more storage space","Anyone with database access could read every user''s password directly","It makes the website slower","Databases don''t support text fields"],"de":["Es verbraucht mehr Speicherplatz","Jeder mit Datenbankzugriff könnte jedes Passwort direkt lesen","Es macht die Website langsamer","Datenbanken unterstützen keine Textfelder"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-security-checkpoint-exam')
);

