-- CodePath Academy — Deployment/DevOps unit (Tools) + deeper Backend unit
-- Two things in one file:
-- 1. 4 more free Tools lessons (devops-what-is-deployment through
--    devops-final-project, sort_order 9-12, appended after tools-cloud-and-ai
--    at 8): what deployment means, environment variables/secrets, CI/CD
--    basics, and a pre-deploy-checklist final project. Leans on this
--    platform's own real Vercel+GitHub setup as the concrete example
--    throughout, continuing tools-cloud-and-ai's pattern.
-- 2. 4 more paid-tier Backend lessons (backend-transactions through
--    backend-deep-final-project, sort_order 23-26, appended after
--    backend-fullstack-capstone at 22): transactions, indexes, API
--    versioning/pagination, and a final project combining all three.
--    Same simulated-array pattern already used throughout Backend (no
--    real database connection exists in the sandbox).
--
-- This closes out every item on the "not a full course yet" gap list.
-- Safe to paste more than once — every insert is guarded with
-- "where not exists".
--
-- Generated by gen-devops-and-backend-deep2.js — don't hand-edit, regenerate.

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'tools'),
  'devops-what-is-deployment',
  '{"en":"What Is Deployment?","de":"Was ist Deployment?"}'::jsonb,
  '[{"step":1,"text":{"en":"Code running on your own computer only you can see. Deployment is the process of putting your code on a server that''s reachable by anyone on the internet — turning \"it works on my machine\" into a real, live website.","de":"Code, der auf deinem eigenen Computer läuft, kann nur von dir gesehen werden. Deployment ist der Vorgang, deinen Code auf einen Server zu bringen, der von jedem im Internet erreichbar ist — aus \"funktioniert auf meinem Rechner\" wird eine echte, live Website."}},{"step":2,"text":{"en":"This platform deploys itself this exact way: the code lives on GitHub, and a hosting service (Vercel) watches that repository and automatically builds and deploys a new live version every time new code is pushed.","de":"Diese Plattform deployt sich selbst genau so: Der Code liegt auf GitHub, und ein Hosting-Dienst (Vercel) beobachtet dieses Repository und baut und deployt automatisch eine neue Live-Version, sobald neuer Code gepusht wird."}},{"step":3,"text":{"en":"\"Production\" is the common name for the live version real users see, as opposed to the version running only on your own machine while you''re building it.","de":"\"Produktion\" (Production) ist der gängige Name für die Live-Version, die echte Nutzer sehen, im Gegensatz zu der Version, die nur auf deinem eigenen Rechner läuft, während du sie baust."}}]'::jsonb,
  null,
  'beginner', true, false,
  9
where not exists (select 1 from lessons where slug = 'devops-what-is-deployment');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'devops-what-is-deployment'),
  '{"en":"What does \"deployment\" mean?","de":"Was bedeutet \"Deployment\"?"}'::jsonb,
  '{"en":["Deleting old code","Putting your code on a server reachable by anyone on the internet","Writing tests","Choosing a color scheme"],"de":["Alten Code löschen","Deinen Code auf einen Server bringen, der von jedem im Internet erreichbar ist","Tests schreiben","Ein Farbschema wählen"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'devops-what-is-deployment')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'tools'),
  'devops-environment-variables',
  '{"en":"Environment Variables & Secrets","de":"Umgebungsvariablen & Geheimnisse"}'::jsonb,
  '[{"step":1,"text":{"en":"An environment variable is a named value the code reads at runtime instead of having hardcoded — this platform''s own Supabase URL and API keys are read this way, from NEXT_PUBLIC_SUPABASE_URL and friends.","de":"Eine Umgebungsvariable ist ein benannter Wert, den der Code zur Laufzeit ausliest, statt ihn fest im Code zu haben — die eigene Supabase-URL und die API-Schlüssel dieser Plattform werden genau so gelesen, aus NEXT_PUBLIC_SUPABASE_URL und ähnlichen."}},{"step":2,"text":{"en":"This solves two real problems at once: the same code can run with different settings in different places (a test database locally, a real one in production), and secret values never end up committed into Git where anyone with repo access could read them.","de":"Das löst zwei echte Probleme gleichzeitig: derselbe Code kann an verschiedenen Orten mit unterschiedlichen Einstellungen laufen (eine Test-Datenbank lokal, eine echte in Produktion), und geheime Werte landen nie in Git, wo jeder mit Repo-Zugriff sie lesen könnte."}},{"step":3,"text":{"en":"That''s exactly why .env.local is listed in .gitignore in a real project — the values live only on your machine and on the hosting service''s dashboard (like Vercel''s environment variables settings), never inside the code itself.","de":"Genau deshalb steht .env.local in einem echten Projekt in der .gitignore — die Werte existieren nur auf deinem Rechner und im Dashboard des Hosting-Dienstes (wie den Umgebungsvariablen-Einstellungen von Vercel), niemals im Code selbst."}}]'::jsonb,
  '{"js":"// Never hardcode real secrets directly in your code, like this:\n// const apiKey = \"sk_live_abc123...\";\n\n// Instead, code reads a secret from the environment at runtime:\nfunction getApiKey(env) {\n  return env.API_KEY;\n}\n\n// Simulating two different environments the same code can run in:\nconst devEnv = { API_KEY: \"dev-test-key\" };\nconst prodEnv = { API_KEY: \"live-secret-key\" };\n\nconsole.log(\"Dev:\", getApiKey(devEnv));\nconsole.log(\"Prod:\", getApiKey(prodEnv));\n"}'::jsonb,
  'beginner', true, false,
  10
where not exists (select 1 from lessons where slug = 'devops-environment-variables');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'devops-environment-variables'),
  '{"en":"Why should real secrets (API keys, passwords) never be hardcoded directly in your source code?","de":"Warum sollten echte Geheimnisse (API-Schlüssel, Passwörter) niemals direkt im Quellcode fest hinterlegt werden?"}'::jsonb,
  '{"en":["It makes the code run slower","Anyone with access to the code/Git history could read and misuse them","JavaScript doesn''t allow it","It''s fine, as long as the code isn''t public"],"de":["Es macht den Code langsamer","Jeder mit Zugriff auf den Code/die Git-Historie könnte sie lesen und missbrauchen","JavaScript erlaubt das nicht","Es ist in Ordnung, solange der Code nicht öffentlich ist"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'devops-environment-variables')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'tools'),
  'devops-ci-cd-basics',
  '{"en":"CI/CD: Automating Build & Deploy","de":"CI/CD: Build & Deploy automatisieren"}'::jsonb,
  '[{"step":1,"text":{"en":"CI (Continuous Integration) means every push automatically runs checks — installing dependencies, running tests, making sure the build succeeds — before anything is considered safe to ship.","de":"CI (Continuous Integration) bedeutet, dass jeder Push automatisch Prüfungen auslöst — Abhängigkeiten installieren, Tests ausführen, sicherstellen, dass der Build gelingt — bevor irgendetwas als sicher zum Ausliefern gilt."}},{"step":2,"text":{"en":"CD (Continuous Deployment) means that once those checks pass, the new version goes live automatically — no manual upload step. This is exactly what happens on this platform: git push, and Vercel builds and deploys by itself.","de":"CD (Continuous Deployment) bedeutet, dass die neue Version automatisch live geht, sobald diese Prüfungen bestanden sind — kein manueller Upload-Schritt. Genau das passiert auf dieser Plattform: git push, und Vercel baut und deployt von selbst."}},{"step":3,"text":{"en":"The real value: if any step fails (like a test breaking), the pipeline stops before broken code ever reaches real users — run the starter code and change one step''s run() to return false to see this in action.","de":"Der eigentliche Wert: Wenn ein Schritt fehlschlägt (z. B. ein kaputter Test), stoppt die Pipeline, bevor kaputter Code echte Nutzer erreicht — führe den Startcode aus und ändere die run()-Funktion eines Schritts auf false, um das in Aktion zu sehen."}}]'::jsonb,
  '{"js":"// A simplified simulation of what a CI/CD pipeline actually does\n// every time code is pushed — this platform''s own Vercel setup runs\n// through exactly these steps for real, automatically.\nfunction deployPipeline(steps) {\n  for (const step of steps) {\n    console.log(\"Running: \" + step.name);\n    if (!step.run()) {\n      console.log(\"FAILED at: \" + step.name + \" \\u2014 deploy stopped.\");\n      return;\n    }\n  }\n  console.log(\"Deployed to production.\");\n}\n\ndeployPipeline([\n  { name: \"install dependencies\", run: () => true },\n  { name: \"run tests\", run: () => true },\n  { name: \"build\", run: () => true },\n  { name: \"deploy\", run: () => true },\n]);\n"}'::jsonb,
  'intermediate', true, false,
  11
where not exists (select 1 from lessons where slug = 'devops-ci-cd-basics');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'devops-ci-cd-basics'),
  '{"en":"What''s the point of running tests automatically as part of a CI/CD pipeline?","de":"Was bringt es, Tests automatisch als Teil einer CI/CD-Pipeline auszuführen?"}'::jsonb,
  '{"en":["To slow down deployment on purpose","To catch broken code before it reaches real users, not after","Tests are required by law","It changes the website''s colors"],"de":["Um das Deployment absichtlich zu verlangsamen","Um kaputten Code zu erkennen, bevor er echte Nutzer erreicht, nicht danach","Tests sind gesetzlich vorgeschrieben","Es ändert die Farben der Website"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'devops-ci-cd-basics')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'tools'),
  'devops-final-project',
  '{"en":"Project: A Pre-Deploy Checklist","de":"Projekt: Eine Pre-Deploy-Checkliste"}'::jsonb,
  '[{"step":1,"text":{"en":"Final project: real teams use a pre-deploy checklist to catch problems before they ship, not after — the same idea as the tests and CI/CD pipeline you just learned, made concrete.","de":"Abschlussprojekt: Echte Teams nutzen eine Pre-Deploy-Checkliste, um Probleme vor dem Ausliefern zu erkennen, nicht danach — dieselbe Idee wie die Tests und die CI/CD-Pipeline, die du gerade gelernt hast, konkret gemacht."}},{"step":2,"text":{"en":"The starter code models a checklist as an array of { name, check() } items, and reports exactly which ones failed — the same shape a real automated deploy gate would use.","de":"Der Startcode modelliert eine Checkliste als Array von { name, check() }-Elementen und meldet genau, welche fehlgeschlagen sind — dieselbe Form, die ein echtes automatisiertes Deploy-Gate nutzen würde."}},{"step":3,"text":{"en":"Add at least 2 more realistic checklist items, then deliberately make one check() return false and confirm the failure output lists exactly the right item — then submit the finished file to your portfolio.","de":"Füge mindestens 2 weitere realistische Checklisten-Punkte hinzu, lass dann absichtlich eine check()-Funktion false zurückgeben und bestätige, dass die Fehlerausgabe genau den richtigen Punkt auflistet — reiche die fertige Datei dann in dein Portfolio ein."}}]'::jsonb,
  '{"js":"const checklist = [\n  { name: \"All tests passing\", check: () => true },\n  { name: \"No secrets hardcoded in source\", check: () => true },\n  { name: \"Environment variables set on host\", check: () => true },\n  { name: \"Build succeeds locally\", check: () => true },\n];\n\nfunction runChecklist(items) {\n  const failed = items.filter((item) => !item.check());\n  if (failed.length === 0) {\n    console.log(\"\\u2705 Ready to deploy.\");\n  } else {\n    console.log(\"\\u274c Not ready:\");\n    failed.forEach((f) => console.log(\"  - \" + f.name));\n  }\n}\n\nrunChecklist(checklist);\n\n// Your task: add at least 2 more real checklist items (e.g. \"database\n// migrations applied\", \"no console.log left in production code\"),\n// then make one of them fail on purpose and confirm the output changes.\n"}'::jsonb,
  'advanced', true, true,
  12
where not exists (select 1 from lessons where slug = 'devops-final-project');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'devops-final-project'),
  '{"en":"Why model a deploy checklist as a list of automated checks instead of a manual paper list?","de":"Warum eine Deploy-Checkliste als Liste automatisierter Prüfungen statt als manuelle Papierliste modellieren?"}'::jsonb,
  '{"en":["Automated checks can run every single time without being forgotten or skipped","Paper lists are more accurate","It''s required by every hosting provider","It has no real benefit"],"de":["Automatisierte Prüfungen können jedes Mal laufen, ohne vergessen oder übersprungen zu werden","Papierlisten sind genauer","Es ist bei jedem Hosting-Anbieter vorgeschrieben","Es bringt keinen echten Vorteil"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'devops-final-project')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-transactions',
  '{"en":"Database Transactions","de":"Datenbank-Transaktionen"}'::jsonb,
  '[{"step":1,"text":{"en":"A database transaction groups multiple operations into one all-or-nothing unit: either every operation in it succeeds, or none of them are kept at all — nothing is left half-done.","de":"Eine Datenbank-Transaktion fasst mehrere Operationen zu einer Alles-oder-nichts-Einheit zusammen: Entweder gelingen alle Operationen darin, oder keine davon wird übernommen — nichts bleibt halb erledigt."}},{"step":2,"text":{"en":"The classic example is a money transfer: subtracting from one account and adding to another must both happen, or neither should — a transaction is exactly the tool that guarantees this, even if the server crashes mid-way.","de":"Das klassische Beispiel ist eine Geldüberweisung: Von einem Konto abziehen und einem anderen gutschreiben müssen beide passieren, oder keines von beidem — eine Transaktion ist genau das Werkzeug, das dies garantiert, selbst wenn der Server mittendrin abstürzt."}},{"step":3,"text":{"en":"In real PostgreSQL (the database this platform itself uses via Supabase), this is written as BEGIN; ...your statements...; COMMIT; — with ROLLBACK available to undo everything if something goes wrong partway through.","de":"In echtem PostgreSQL (der Datenbank, die diese Plattform selbst über Supabase nutzt) schreibt man das als BEGIN; ...deine Anweisungen...; COMMIT; — mit ROLLBACK, um alles rückgängig zu machen, falls mittendrin etwas schiefgeht."}}]'::jsonb,
  '{"js":"// Simulated bank transfer WITHOUT a transaction — dangerous if it\n// crashes halfway through.\nfunction transferUnsafe(accounts, from, to, amount) {\n  accounts[from] -= amount;\n  // Imagine a crash happens right here, before the next line runs —\n  // the money would just vanish, taken from one account, never added\n  // to the other.\n  accounts[to] += amount;\n}\n\n// A transaction wraps both steps as one all-or-nothing unit.\nfunction transferWithTransaction(accounts, from, to, amount) {\n  const before = { ...accounts };\n  try {\n    accounts[from] -= amount;\n    accounts[to] += amount;\n  } catch (err) {\n    Object.assign(accounts, before); // roll back everything\n    throw err;\n  }\n}\n\nconst accounts = { alice: 100, bob: 50 };\ntransferWithTransaction(accounts, \"alice\", \"bob\", 30);\nconsole.log(accounts);\n"}'::jsonb,
  'intermediate', false, false,
  23
where not exists (select 1 from lessons where slug = 'backend-transactions');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-transactions'),
  '{"en":"What guarantee does a database transaction provide?","de":"Welche Garantie bietet eine Datenbank-Transaktion?"}'::jsonb,
  '{"en":["It makes queries run faster","All its operations succeed together, or none of them are kept","It automatically creates backups","It changes the table''s column names"],"de":["Sie macht Abfragen schneller","Alle ihre Operationen gelingen gemeinsam, oder keine davon wird übernommen","Sie erstellt automatisch Backups","Sie ändert die Spaltennamen der Tabelle"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-transactions')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-database-indexes',
  '{"en":"Database Indexes","de":"Datenbank-Indizes"}'::jsonb,
  '[{"step":1,"text":{"en":"Without help, a database looks up a row by checking every single row one at a time — fine for a handful of rows, painfully slow once a table has millions.","de":"Ohne Hilfe sucht eine Datenbank eine Zeile, indem sie jede einzelne Zeile nacheinander prüft — kein Problem bei einer Handvoll Zeilen, quälend langsam, sobald eine Tabelle Millionen hat."}},{"step":2,"text":{"en":"An index is a separate, pre-built lookup structure for one column (like email) that lets the database jump almost straight to the matching row instead of scanning everything — the Map in the starter code simulates exactly this idea.","de":"Ein Index ist eine separate, im Voraus aufgebaute Nachschlagestruktur für eine Spalte (wie email), die es der Datenbank erlaubt, fast direkt zur passenden Zeile zu springen, statt alles zu durchsuchen — die Map im Startcode simuliert genau diese Idee."}},{"step":3,"text":{"en":"Indexes aren''t free: they speed up lookups but slightly slow down writes (the index itself has to be updated too), and take extra storage — this platform''s own schema.sql already creates real indexes like the unique index on subscriptions.stripe_customer_id.","de":"Indizes sind nicht kostenlos: Sie beschleunigen Lookups, verlangsamen aber Schreibvorgänge leicht (der Index selbst muss ebenfalls aktualisiert werden) und brauchen zusätzlichen Speicher — das eigene schema.sql dieser Plattform erstellt bereits echte Indizes, wie den eindeutigen Index auf subscriptions.stripe_customer_id."}}]'::jsonb,
  '{"js":"// Simulating why an index matters, without a real database.\nconst users = Array.from({ length: 10000 }, (_, i) => ({\n  id: i,\n  email: \"user\" + i + \"@example.com\",\n}));\n\n// Without an index: check every single row one by one.\nfunction findByEmailSlow(email) {\n  for (const user of users) {\n    if (user.email === email) return user;\n  }\n  return null;\n}\n\n// With an index: a lookup table built once, ahead of time.\nconst emailIndex = new Map(users.map((u) => [u.email, u]));\nfunction findByEmailFast(email) {\n  return emailIndex.get(email) ?? null;\n}\n\nconsole.log(findByEmailSlow(\"user9999@example.com\"));\nconsole.log(findByEmailFast(\"user9999@example.com\"));\n"}'::jsonb,
  'intermediate', false, false,
  24
where not exists (select 1 from lessons where slug = 'backend-database-indexes');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-database-indexes'),
  '{"en":"What does a database index actually do?","de":"Was macht ein Datenbank-Index eigentlich?"}'::jsonb,
  '{"en":["Deletes unused rows automatically","Provides a pre-built lookup structure so matching rows can be found without scanning the whole table","Encrypts the table","Makes every column optional"],"de":["Löscht automatisch ungenutzte Zeilen","Bietet eine im Voraus aufgebaute Nachschlagestruktur, damit passende Zeilen ohne Scan der ganzen Tabelle gefunden werden","Verschlüsselt die Tabelle","Macht jede Spalte optional"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-database-indexes')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-api-versioning-pagination',
  '{"en":"API Versioning & Pagination","de":"API-Versionierung & Pagination"}'::jsonb,
  '[{"step":1,"text":{"en":"APIs change over time, but old clients (an old mobile app version still installed on someone''s phone) can''t update instantly. Versioning the URL itself (/api/v1/... vs /api/v2/...) lets both the old and new shape keep working side by side.","de":"APIs ändern sich mit der Zeit, aber alte Clients (eine alte Mobile-App-Version, die noch auf jemandes Handy installiert ist) können nicht sofort aktualisieren. Die URL selbst zu versionieren (/api/v1/... vs /api/v2/...) lässt die alte und die neue Form nebeneinander weiterlaufen."}},{"step":2,"text":{"en":"Pagination means never sending an entire huge table in one response — instead the client asks for one page at a time (e.g. 10 items), and the server reports how many pages exist in total.","de":"Pagination bedeutet, niemals eine ganze riesige Tabelle in einer einzigen Antwort zu senden — stattdessen fragt der Client jeweils eine Seite an (z. B. 10 Elemente), und der Server meldet, wie viele Seiten es insgesamt gibt."}},{"step":3,"text":{"en":"Without pagination, a table that grows from 100 rows to 100,000 rows would eventually make every single request slower and slower — pagination keeps each individual response small and fast, no matter how much data exists overall.","de":"Ohne Pagination würde eine Tabelle, die von 100 auf 100.000 Zeilen wächst, mit der Zeit jede einzelne Anfrage immer langsamer machen — Pagination hält jede einzelne Antwort klein und schnell, egal wie viele Daten insgesamt existieren."}}]'::jsonb,
  '{"js":"// Versioning: the URL itself carries which version of the API this is.\nfunction handleRequest(path) {\n  if (path.startsWith(\"/api/v1/lessons\")) return { format: \"old shape\" };\n  if (path.startsWith(\"/api/v2/lessons\")) return { format: \"new shape\" };\n  return { status: 404 };\n}\n\nconsole.log(handleRequest(\"/api/v1/lessons\"));\nconsole.log(handleRequest(\"/api/v2/lessons\"));\n\n// Pagination: never return 10,000 rows in one response.\nconst allLessons = Array.from({ length: 63 }, (_, i) => \"Lesson \" + (i + 1));\nfunction paginate(items, page, pageSize) {\n  const start = (page - 1) * pageSize;\n  return {\n    items: items.slice(start, start + pageSize),\n    page,\n    totalPages: Math.ceil(items.length / pageSize),\n  };\n}\n\nconsole.log(paginate(allLessons, 2, 10));\n"}'::jsonb,
  'intermediate', false, false,
  25
where not exists (select 1 from lessons where slug = 'backend-api-versioning-pagination');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-api-versioning-pagination'),
  '{"en":"Why do real APIs paginate large result sets instead of returning everything at once?","de":"Warum paginieren echte APIs große Ergebnismengen, statt alles auf einmal zurückzugeben?"}'::jsonb,
  '{"en":["To make the API harder to use on purpose","To keep each response small and fast regardless of how much total data exists","Pagination is required by every browser","It has no real purpose"],"de":["Um die API absichtlich schwerer nutzbar zu machen","Um jede Antwort klein und schnell zu halten, egal wie viele Daten insgesamt existieren","Pagination ist von jedem Browser vorgeschrieben","Es hat keinen echten Zweck"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-api-versioning-pagination')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'backend'),
  'backend-deep-final-project',
  '{"en":"Project: A Paginated Orders API","de":"Projekt: Eine paginierte Bestellungen-API"}'::jsonb,
  '[{"step":1,"text":{"en":"Final project: combine everything from this deeper-backend unit — an indexed lookup, paginated listing, and a transaction-style all-or-nothing update — into one small orders API.","de":"Abschlussprojekt: Kombiniere alles aus dieser vertieften Backend-Einheit — einen indizierten Lookup, eine paginierte Auflistung und ein transaktionsartiges Alles-oder-nichts-Update — zu einer kleinen Bestellungen-API."}},{"step":2,"text":{"en":"getOrder uses the same Map-based index idea from the indexes lesson; listOrders uses the same pagination shape from the previous lesson — nothing new to learn there, just applied together.","de":"getOrder nutzt dieselbe Map-basierte Index-Idee aus der Index-Lektion; listOrders nutzt dieselbe Pagination-Form aus der vorherigen Lektion — nichts Neues zu lernen, nur gemeinsam angewendet."}},{"step":3,"text":{"en":"Write refundOrder(id, amount): look the order up, verify amount doesn''t exceed its total, then update it — if anything is invalid, throw instead of partially applying the change, then submit the finished file to your portfolio.","de":"Schreibe refundOrder(id, amount): Suche die Bestellung, prüfe, dass amount nicht über dem total liegt, und aktualisiere sie dann — ist etwas ungültig, wirf einen Fehler, statt die Änderung nur teilweise anzuwenden, und reiche die fertige Datei dann in dein Portfolio ein."}}]'::jsonb,
  '{"js":"const orders = Array.from({ length: 47 }, (_, i) => ({\n  id: i + 1,\n  total: Math.round(Math.random() * 100),\n}));\n\n// A simulated index for fast lookup by id.\nconst ordersById = new Map(orders.map((o) => [o.id, o]));\n\nfunction getOrder(id) {\n  return ordersById.get(id) ?? null;\n}\n\nfunction listOrders(page, pageSize) {\n  const start = (page - 1) * pageSize;\n  return {\n    items: orders.slice(start, start + pageSize),\n    page,\n    totalPages: Math.ceil(orders.length / pageSize),\n  };\n}\n\n// Your task: write refundOrder(id, amount) that finds the order via\n// ordersById, checks amount doesn''t exceed order.total, and either\n// applies the refund (subtract from total) or throws an error —\n// wrap the check-then-update as a single all-or-nothing step, the\n// same transaction idea from earlier in this unit.\n\nconsole.log(listOrders(1, 10));\nconsole.log(getOrder(5));\n"}'::jsonb,
  'advanced', false, true,
  26
where not exists (select 1 from lessons where slug = 'backend-deep-final-project');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'backend-deep-final-project'),
  '{"en":"Which three ideas does this final project combine?","de":"Welche drei Ideen kombiniert dieses Abschlussprojekt?"}'::jsonb,
  '{"en":["Indexed lookup, pagination, and an all-or-nothing update","Only CSS Grid and Flexbox","Only React hooks","Only Git branching"],"de":["Indizierter Lookup, Pagination und ein Alles-oder-nichts-Update","Nur CSS Grid und Flexbox","Nur React-Hooks","Nur Git-Branching"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'backend-deep-final-project')
);

