-- CodePath Academy — Foundation expansion + new Tools & Environment course
-- Adds 3 more free Foundation lessons (sort_order 3-5): what a programming
-- language is, your basic toolkit, and a roadmap explaining Frontend vs
-- Backend vs the new Tools section. Also creates a brand-new 4th course,
-- 'tools' (free, independent from Frontend/Backend like every course
-- already is — computeLessonAccess has zero cross-course dependency),
-- covering VS Code, Git & GitHub, and Cloud & AI assistants — the
-- real-world workflow every developer needs regardless of path.
--
-- The 5 existing Git/GitHub lessons (git-what-is-version-control through
-- git-merge-conflicts-project) are MOVED here from Frontend via UPDATE,
-- not duplicated — they were only ever added there because Tools didn't
-- exist yet. Their lesson_progress rows (lesson_id, not course_id-based)
-- are untouched, so no student progress is lost by the move.
--
-- Generated by gen-foundation-and-tools.js — don't hand-edit, regenerate.

insert into courses (slug, title, description, sort_order) values
  ('tools', '{"en":"Tools & Environment","de":"Werkzeuge & Umgebung"}'::jsonb, '{"en":"VS Code, Git & GitHub, and working with the cloud and AI assistants.","de":"VS Code, Git & GitHub sowie Arbeiten mit der Cloud und KI-Assistenten."}'::jsonb, 4)
on conflict (slug) do nothing;

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'foundation'),
  'foundation-programming-languages',
  '{"en":"What Is a Programming Language?","de":"Was ist eine Programmiersprache?"}'::jsonb,
  '[{"step":1,"text":{"en":"Computers only understand very simple electrical signals. A programming language is a human-readable way to write instructions that eventually get translated down to those signals.","de":"Computer verstehen nur sehr einfache elektrische Signale. Eine Programmiersprache ist eine für Menschen lesbare Art, Anweisungen zu schreiben, die am Ende in diese Signale übersetzt werden."}},{"step":2,"text":{"en":"There isn''t just one programming language — different languages exist for different jobs. This course focuses on the languages that build the web: HTML and CSS for what you see, JavaScript for behavior, and Node.js (still JavaScript) for what runs behind the scenes.","de":"Es gibt nicht nur eine Programmiersprache — verschiedene Sprachen existieren für verschiedene Aufgaben. Dieser Kurs konzentriert sich auf die Sprachen, die das Web bauen: HTML und CSS für das, was du siehst, JavaScript für das Verhalten, und Node.js (weiterhin JavaScript) für das, was im Hintergrund läuft."}},{"step":3,"text":{"en":"You don''t need to learn every language that exists to become a real developer — you need to deeply understand a focused set. That''s exactly what this course teaches, one growing project at a time.","de":"Du musst nicht jede existierende Sprache lernen, um ein echter Entwickler zu werden — du musst eine fokussierte Auswahl tief verstehen. Genau das lehrt dieser Kurs, ein wachsendes Projekt nach dem anderen."}}]'::jsonb,
  null,
  'beginner', true, false,
  3
where not exists (select 1 from lessons where slug = 'foundation-programming-languages');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'foundation-programming-languages'),
  '{"en":"Why do different programming languages exist instead of just one?","de":"Warum gibt es verschiedene Programmiersprachen und nicht nur eine?"}'::jsonb,
  '{"en":["Because computers are broken","Different languages are suited to different jobs and platforms","To make learning to code harder on purpose","Only old computers need multiple languages"],"de":["Weil Computer kaputt sind","Verschiedene Sprachen eignen sich für verschiedene Aufgaben und Plattformen","Um das Programmierenlernen absichtlich schwerer zu machen","Nur alte Computer brauchen mehrere Sprachen"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'foundation-programming-languages')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'foundation'),
  'foundation-your-toolkit',
  '{"en":"Your Toolkit: Editor, Browser, Console","de":"Dein Werkzeugkasten: Editor, Browser, Konsole"}'::jsonb,
  '[{"step":1,"text":{"en":"Every developer works with three basic tools: a code editor (where you write instructions), a browser (where websites actually run), and a console (where you see what''s happening, including errors).","de":"Jeder Entwickler arbeitet mit drei Grundwerkzeugen: einem Code-Editor (wo du Anweisungen schreibst), einem Browser (wo Websites tatsächlich laufen) und einer Konsole (wo du siehst, was passiert, einschließlich Fehler)."}},{"step":2,"text":{"en":"This course''s built-in editor is a simplified version of the real tool most professionals use — Visual Studio Code (VS Code). You''ll learn the real thing properly in the dedicated Tools section later in your roadmap.","de":"Der in diesen Kurs eingebaute Editor ist eine vereinfachte Version des echten Tools, das die meisten Profis nutzen — Visual Studio Code (VS Code). Das echte Tool lernst du später im dedizierten Werkzeuge-Bereich deines Fahrplans richtig kennen."}},{"step":3,"text":{"en":"The console isn''t just for errors — console.log() lets you \"peek inside\" your code while it''s running, which is the single most useful debugging habit you''ll build in this whole course.","de":"Die Konsole ist nicht nur für Fehler da — mit console.log() kannst du \"in deinen Code hineinschauen\", während er läuft. Das ist die nützlichste Debugging-Gewohnheit, die du in diesem ganzen Kurs aufbauen wirst."}}]'::jsonb,
  null,
  'beginner', true, false,
  4
where not exists (select 1 from lessons where slug = 'foundation-your-toolkit');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'foundation-your-toolkit'),
  '{"en":"What is the console mainly used for?","de":"Wofür wird die Konsole hauptsächlich genutzt?"}'::jsonb,
  '{"en":["Seeing what your code is doing while it runs, including errors","Changing the color of your website","Sending emails","Deleting files permanently"],"de":["Zu sehen, was dein Code beim Ausführen macht, inklusive Fehler","Die Farbe deiner Website zu ändern","E-Mails zu versenden","Dateien dauerhaft zu löschen"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'foundation-your-toolkit')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'foundation'),
  'foundation-your-roadmap',
  '{"en":"Your Roadmap: Frontend, Backend & Tools","de":"Dein Fahrplan: Frontend, Backend & Werkzeuge"}'::jsonb,
  '[{"step":1,"text":{"en":"After Foundation, you''ll choose a path. Frontend takes you through HTML, then CSS, then JavaScript, then React — everything a user actually sees and clicks. Backend takes you through servers, Node.js, Express, databases, and authentication — everything running behind the scenes.","de":"Nach Foundation wählst du einen Pfad. Frontend führt dich durch HTML, dann CSS, dann JavaScript, dann React — alles, was ein Nutzer wirklich sieht und anklickt. Backend führt dich durch Server, Node.js, Express, Datenbanken und Authentifizierung — alles, was im Hintergrund läuft."}},{"step":2,"text":{"en":"You don''t have to pick just one. Frontend and Backend are independent paths — you can do either first, switch anytime, or eventually do both, exactly like most real working developers do.","de":"Du musst nicht nur einen wählen. Frontend und Backend sind unabhängige Pfade — du kannst mit einem beliebigen anfangen, jederzeit wechseln oder irgendwann beide machen, genau wie es die meisten echten Entwickler tun."}},{"step":3,"text":{"en":"Alongside both, a separate Tools section teaches the real-world workflow every developer needs regardless of path: your code editor (VS Code), version control (Git & GitHub), and working with the cloud and AI coding assistants.","de":"Neben beiden lehrt ein eigener Werkzeuge-Bereich den echten Arbeitsablauf, den jeder Entwickler unabhängig vom Pfad braucht: dein Code-Editor (VS Code), Versionskontrolle (Git & GitHub) sowie Arbeiten mit der Cloud und KI-Coding-Assistenten."}}]'::jsonb,
  null,
  'beginner', true, false,
  5
where not exists (select 1 from lessons where slug = 'foundation-your-roadmap');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'foundation-your-roadmap'),
  '{"en":"According to your roadmap, do you have to fully finish Frontend before starting Backend?","de":"Musst du laut deinem Fahrplan Frontend komplett abschließen, bevor du mit Backend beginnst?"}'::jsonb,
  '{"en":["Yes, Backend is locked until Frontend is 100% done","No — they''re independent paths, you can do either or both in any order","No, you can only ever do one of them","Yes, but only on weekends"],"de":["Ja, Backend ist gesperrt, bis Frontend zu 100 % fertig ist","Nein — sie sind unabhängige Pfade, du kannst beide in beliebiger Reihenfolge machen","Nein, du kannst nur jemals eines davon machen","Ja, aber nur an Wochenenden"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'foundation-your-roadmap')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'tools'),
  'tools-what-is-vscode',
  '{"en":"Meet VS Code","de":"Lerne VS Code kennen"}'::jsonb,
  '[{"step":1,"text":{"en":"VS Code (Visual Studio Code) is the most widely used code editor among professional developers — free, made by Microsoft, and available on Windows, Mac, and Linux.","de":"VS Code (Visual Studio Code) ist der am weitesten verbreitete Code-Editor unter professionellen Entwicklern — kostenlos, von Microsoft, verfügbar für Windows, Mac und Linux."}},{"step":2,"text":{"en":"It highlights your code by language (syntax highlighting), points out mistakes as you type, and supports thousands of extensions that add extra features on top of the basics.","de":"Er hebt deinen Code je nach Sprache farblich hervor (Syntax-Highlighting), zeigt Fehler schon beim Tippen an und unterstützt Tausende Erweiterungen, die zusätzliche Funktionen hinzufügen."}},{"step":3,"text":{"en":"This platform''s built-in editor deliberately mimics VS Code''s dark theme and file-tab layout — what you''re already used to here will feel immediately familiar the moment you open real VS Code.","de":"Der in diese Plattform eingebaute Editor ahmt bewusst das dunkle Design und die Datei-Tab-Ansicht von VS Code nach — was du hier schon gewohnt bist, wird dir in echtem VS Code sofort vertraut vorkommen."}}]'::jsonb,
  null,
  'beginner', true, false,
  1
where not exists (select 1 from lessons where slug = 'tools-what-is-vscode');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'tools-what-is-vscode'),
  '{"en":"What is VS Code?","de":"Was ist VS Code?"}'::jsonb,
  '{"en":["A web browser","A free, widely used code editor","A programming language","A database"],"de":["Ein Webbrowser","Ein kostenloser, weit verbreiteter Code-Editor","Eine Programmiersprache","Eine Datenbank"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'tools-what-is-vscode')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'tools'),
  'tools-vscode-workflow',
  '{"en":"A Real VS Code Workflow","de":"Ein echter VS Code Workflow"}'::jsonb,
  '[{"step":1,"text":{"en":"In real VS Code, you open a whole project folder, not a single file — the sidebar on the left shows every file in it, and you click between them, exactly like the lesson tabs you''ve already been using on this platform.","de":"In echtem VS Code öffnest du einen ganzen Projektordner, nicht nur eine einzelne Datei — die Seitenleiste links zeigt jede Datei darin, und du klickst zwischen ihnen, genau wie bei den Lektions-Tabs, die du auf dieser Plattform schon nutzt."}},{"step":2,"text":{"en":"The Integrated Terminal (View → Terminal, or Ctrl+`) is a command line built right into the editor — this is exactly where you''ll type the git commands from the next lessons, and later run real servers.","de":"Das integrierte Terminal (Ansicht → Terminal, oder Strg+`) ist eine Befehlszeile direkt im Editor — genau dort wirst du die Git-Befehle der nächsten Lektionen eingeben und später echte Server starten."}},{"step":3,"text":{"en":"Extensions add features VS Code doesn''t have built in by default — for example, an extension can auto-format your code or add a live-reloading preview, similar to what this platform''s editor already does for you automatically.","de":"Erweiterungen fügen Funktionen hinzu, die VS Code nicht standardmäßig eingebaut hat — zum Beispiel kann eine Erweiterung deinen Code automatisch formatieren oder eine Live-Vorschau hinzufügen, ähnlich dem, was der Editor dieser Plattform schon automatisch für dich tut."}}]'::jsonb,
  null,
  'beginner', true, false,
  2
where not exists (select 1 from lessons where slug = 'tools-vscode-workflow');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'tools-vscode-workflow'),
  '{"en":"What does VS Code''s Integrated Terminal let you do?","de":"Was ermöglicht dir das integrierte Terminal von VS Code?"}'::jsonb,
  '{"en":["Change the editor''s color theme only","Run command-line commands, like git, without leaving the editor","Send the code to a printer","Nothing, it''s just decoration"],"de":["Nur das Farbschema des Editors ändern","Befehlszeilenbefehle wie git ausführen, ohne den Editor zu verlassen","Den Code an einen Drucker senden","Nichts, es ist nur Dekoration"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'tools-vscode-workflow')
);

-- Move the 5 existing Git/GitHub lessons from Frontend into Tools.
update lessons set course_id = (select id from courses where slug = 'tools'), sort_order = 3
  where slug = 'git-what-is-version-control';
update lessons set course_id = (select id from courses where slug = 'tools'), sort_order = 4
  where slug = 'git-init-and-commit';
update lessons set course_id = (select id from courses where slug = 'tools'), sort_order = 5
  where slug = 'git-branches';
update lessons set course_id = (select id from courses where slug = 'tools'), sort_order = 6
  where slug = 'git-github-remote';
update lessons set course_id = (select id from courses where slug = 'tools'), sort_order = 7
  where slug = 'git-merge-conflicts-project';

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'tools'),
  'tools-cloud-and-ai',
  '{"en":"The Cloud & AI Coding Assistants","de":"Die Cloud & KI-Coding-Assistenten"}'::jsonb,
  '[{"step":1,"text":{"en":"\"The cloud\" just means someone else''s computer, running your code or storing your data, reachable over the internet. This platform itself runs on cloud services: Vercel hosts the website, Supabase hosts the database.","de":"\"Die Cloud\" bedeutet einfach der Computer einer anderen Person, der deinen Code ausführt oder deine Daten speichert und über das Internet erreichbar ist. Diese Plattform selbst läuft auf Cloud-Diensten: Vercel hostet die Website, Supabase hostet die Datenbank."}},{"step":2,"text":{"en":"AI coding assistants (like GitHub Copilot, ChatGPT, or this platform''s own CodeBuddy AI mentor) can suggest code, explain errors, and answer questions — genuinely useful, but only if you still understand what the code actually does.","de":"KI-Coding-Assistenten (wie GitHub Copilot, ChatGPT oder der eigene CodeBuddy-KI-Mentor dieser Plattform) können Code vorschlagen, Fehler erklären und Fragen beantworten — wirklich nützlich, aber nur, wenn du weiterhin verstehst, was der Code tatsächlich macht."}},{"step":3,"text":{"en":"A good rule while learning: use AI to explain a concept you''re stuck on, or to review code you already wrote yourself — not to skip writing the code in the first place. Blindly pasting code you don''t understand is how bugs, and bad habits, creep in.","de":"Eine gute Regel beim Lernen: Nutze KI, um ein Konzept zu erklären, an dem du hängst, oder um Code zu überprüfen, den du selbst geschrieben hast — nicht, um das Schreiben des Codes von vornherein zu überspringen. Blind Code einzufügen, den du nicht verstehst, ist der Weg zu Bugs und schlechten Gewohnheiten."}}]'::jsonb,
  null,
  'intermediate', true, false,
  8
where not exists (select 1 from lessons where slug = 'tools-cloud-and-ai');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'tools-cloud-and-ai'),
  '{"en":"What''s the recommended way to use AI coding assistants while you''re still learning?","de":"Wie sollte man KI-Coding-Assistenten am besten nutzen, während man noch lernt?"}'::jsonb,
  '{"en":["To explain concepts or review your own code, not to skip writing it yourself","To write 100% of your projects for you","AI assistants should never be used at all","Only to fix CSS colors"],"de":["Um Konzepte zu erklären oder eigenen Code zu überprüfen, nicht um das Schreiben zu überspringen","Um 100 % deiner Projekte für dich zu schreiben","KI-Assistenten sollte man nie benutzen","Nur um CSS-Farben zu korrigieren"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'tools-cloud-and-ai')
);

