-- CodePath Academy — Git & GitHub version control unit
-- Appends 5 more paid-tier Frontend lessons (git-what-is-version-control
-- through git-merge-conflicts-project, sort_order 40-44, right after
-- react-final-project at 39). Git/GitHub was a completely missing topic —
-- every professional developer needs it, and it wasn't taught anywhere in
-- the curriculum before this. There's no real terminal in the sandbox, so
-- every lesson simulates git commands through a plain JS git(command)
-- function that logs realistic output — same "simulate what the sandbox
-- can't really run" pattern already used for Backend/React routing/fetching.
-- Safe to paste more than once — every insert is guarded with "where not exists".
--
-- Generated by gen-git-lessons.js — don't hand-edit, regenerate instead.

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'git-what-is-version-control',
  '{"en":"What Is Version Control?","de":"Was ist Versionskontrolle?"}'::jsonb,
  '[{"step":1,"text":{"en":"Every real project needs a way to track changes over time and undo mistakes safely — that''s what version control does.","de":"Jedes echte Projekt braucht eine Möglichkeit, Änderungen über die Zeit nachzuverfolgen und Fehler sicher rückgängig zu machen — genau das macht Versionskontrolle."}},{"step":2,"text":{"en":"Git is the version control system almost every professional team uses. It saves \"snapshots\" of your project called commits, so you can go back to any point in history.","de":"Git ist das Versionskontrollsystem, das fast jedes professionelle Team nutzt. Es speichert \"Schnappschüsse\" deines Projekts, genannt Commits, sodass du zu jedem Punkt in der Geschichte zurückkehren kannst."}},{"step":3,"text":{"en":"GitHub is a website that hosts your Git repositories online — it''s how you back up your code and how teams collaborate on the same project from different computers.","de":"GitHub ist eine Website, die deine Git-Repositories online hostet — so sicherst du deinen Code und so arbeiten Teams von verschiedenen Computern aus am selben Projekt."}}]'::jsonb,
  null,
  'beginner', false, false,
  40
where not exists (select 1 from lessons where slug = 'git-what-is-version-control');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'git-what-is-version-control'),
  '{"en":"What does Git actually save when you make a commit?","de":"Was speichert Git eigentlich, wenn du einen Commit machst?"}'::jsonb,
  '{"en":["A snapshot of your project at that point in time","A backup of your whole computer","Only the file names, not their contents","A video recording of your screen"],"de":["Einen Schnappschuss deines Projekts zu diesem Zeitpunkt","Ein Backup deines ganzen Computers","Nur die Dateinamen, nicht ihren Inhalt","Eine Videoaufnahme deines Bildschirms"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'git-what-is-version-control')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'git-init-and-commit',
  '{"en":"Saving Your Work: init and commit","de":"Deine Arbeit speichern: init und commit"}'::jsonb,
  '[{"step":1,"text":{"en":"git init turns a folder into a Git repository — from that point on, Git starts watching it for changes.","de":"git init verwandelt einen Ordner in ein Git-Repository — ab diesem Moment beobachtet Git ihn auf Änderungen."}},{"step":2,"text":{"en":"A changed file starts out \"unstaged\". git add <file> tells Git which changes you want to include in your next snapshot.","de":"Eine geänderte Datei ist zunächst \"unstaged\". git add <datei> sagt Git, welche Änderungen in deinen nächsten Schnappschuss sollen."}},{"step":3,"text":{"en":"git commit -m \"message\" saves a permanent snapshot of everything staged, together with a message describing what changed and why.","de":"git commit -m \"nachricht\" speichert einen dauerhaften Schnappschuss von allem Staged, zusammen mit einer Nachricht, die beschreibt, was sich geändert hat und warum."}},{"step":4,"text":{"en":"The starter code simulates real git output in the console. Run it, then try staging and committing a second file yourself.","de":"Der Startcode simuliert echte Git-Ausgaben in der Konsole. Führe ihn aus und versuche dann selbst, eine zweite Datei zu stagen und zu committen."}}]'::jsonb,
  '{"js":"// A tiny simulated Git — logs what a real git command would print.\nlet staged = [];\nlet commits = [];\n\nfunction git(command) {\n  if (command === \"init\") {\n    console.log(\"Initialized empty Git repository\");\n  } else if (command.startsWith(\"add \")) {\n    const file = command.slice(4);\n    staged.push(file);\n    console.log(\"Staged: \" + file);\n  } else if (command.startsWith(\"commit -m \")) {\n    const message = command.slice(11, -1);\n    commits.push({ message, files: staged });\n    console.log(\"[main] \" + message + \" (\" + staged.length + \" file(s))\");\n    staged = [];\n  }\n}\n\ngit(\"init\");\ngit(\"add index.html\");\ngit(''commit -m \"first commit\"'');\n"}'::jsonb,
  'beginner', false, false,
  41
where not exists (select 1 from lessons where slug = 'git-init-and-commit');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'git-init-and-commit'),
  '{"en":"What does git add actually do?","de":"Was macht git add eigentlich?"}'::jsonb,
  '{"en":["Permanently saves the file forever","Marks a change to be included in the next commit","Uploads the file to GitHub","Deletes the file"],"de":["Speichert die Datei dauerhaft für immer","Markiert eine Änderung für den nächsten Commit","Lädt die Datei zu GitHub hoch","Löscht die Datei"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'git-init-and-commit')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'git-branches',
  '{"en":"Branches: Working Without Breaking Things","de":"Branches: Arbeiten, ohne etwas kaputtzumachen"}'::jsonb,
  '[{"step":1,"text":{"en":"A branch is a separate line of work — you can try something new on a branch without touching the working version on main at all.","de":"Ein Branch ist eine eigene Arbeitslinie — du kannst darauf etwas Neues ausprobieren, ohne die funktionierende Version auf main überhaupt zu berühren."}},{"step":2,"text":{"en":"git checkout -b feature-name creates a new branch and switches to it in one step. Any commits you make now only exist on that branch.","de":"git checkout -b feature-name erstellt einen neuen Branch und wechselt in einem Schritt dorthin. Alle Commits, die du jetzt machst, existieren nur auf diesem Branch."}},{"step":3,"text":{"en":"Once the work on your branch is finished and tested, you merge it back into main — combining the two histories into one.","de":"Sobald die Arbeit auf deinem Branch fertig und getestet ist, mergst du sie zurück in main — die beiden Verläufe werden zu einem zusammengeführt."}}]'::jsonb,
  '{"js":"// Simulated branching — tracks which branch is \"checked out\".\nlet currentBranch = \"main\";\nconst branches = [\"main\"];\n\nfunction git(command) {\n  if (command.startsWith(\"checkout -b \")) {\n    const name = command.slice(12);\n    branches.push(name);\n    currentBranch = name;\n    console.log(\"Switched to a new branch ''\" + name + \"''\");\n  } else if (command.startsWith(\"checkout \")) {\n    currentBranch = command.slice(9);\n    console.log(\"Switched to branch ''\" + currentBranch + \"''\");\n  } else if (command === \"branch\") {\n    branches.forEach((b) => console.log((b === currentBranch ? \"* \" : \"  \") + b));\n  }\n}\n\ngit(\"checkout -b feature-navbar\");\ngit(\"branch\");\ngit(\"checkout main\");\n"}'::jsonb,
  'intermediate', false, false,
  42
where not exists (select 1 from lessons where slug = 'git-branches');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'git-branches'),
  '{"en":"Why create a separate branch instead of committing straight to main?","de":"Warum einen eigenen Branch erstellen, statt direkt auf main zu committen?"}'::jsonb,
  '{"en":["It makes Git run faster","So you can experiment without risking the working main version","Branches are required by GitHub","It automatically fixes bugs"],"de":["Es macht Git schneller","Damit du experimentieren kannst, ohne die funktionierende main-Version zu riskieren","Branches sind von GitHub vorgeschrieben","Es behebt automatisch Fehler"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'git-branches')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'git-github-remote',
  '{"en":"GitHub: Pushing Your Code Online","de":"GitHub: Deinen Code online hochladen"}'::jsonb,
  '[{"step":1,"text":{"en":"Your local Git repository only exists on your own computer until you connect it to a remote — usually a repository on GitHub.","de":"Dein lokales Git-Repository existiert nur auf deinem eigenen Computer, bis du es mit einem Remote verbindest — meist einem Repository auf GitHub."}},{"step":2,"text":{"en":"git remote add origin <url> links your local repo to that GitHub repository, under the name \"origin\". git push origin main then uploads your commits to it.","de":"git remote add origin <url> verknüpft dein lokales Repository mit diesem GitHub-Repository unter dem Namen \"origin\". git push origin main lädt dann deine Commits dorthin hoch."}},{"step":3,"text":{"en":"git pull downloads any changes that were pushed since your last pull — by you from another computer, or by a teammate — keeping everyone in sync.","de":"git pull lädt alle Änderungen herunter, die seit deinem letzten pull gepusht wurden — von dir selbst an einem anderen Computer oder von einem Teammitglied — und hält alle synchron."}}]'::jsonb,
  '{"js":"// Simulated remote — no real network call, just realistic log output.\nlet remoteUrl = null;\nlet pushedCommits = 0;\n\nfunction git(command) {\n  if (command.startsWith(\"remote add origin \")) {\n    remoteUrl = command.slice(19);\n    console.log(\"Remote ''origin'' set to \" + remoteUrl);\n  } else if (command === \"push origin main\") {\n    pushedCommits += 3;\n    console.log(\"Enumerating objects... done.\");\n    console.log(\"To \" + remoteUrl);\n    console.log(\"main -> main\");\n  } else if (command === \"pull\") {\n    console.log(\"Already up to date.\");\n  }\n}\n\ngit(\"remote add origin https://github.com/you/project.git\");\ngit(\"push origin main\");\ngit(\"pull\");\n"}'::jsonb,
  'intermediate', false, false,
  43
where not exists (select 1 from lessons where slug = 'git-github-remote');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'git-github-remote'),
  '{"en":"What does git push actually do?","de":"Was macht git push eigentlich?"}'::jsonb,
  '{"en":["Downloads changes from GitHub","Deletes your local commits","Uploads your local commits to the remote repository","Creates a new branch"],"de":["Lädt Änderungen von GitHub herunter","Löscht deine lokalen Commits","Lädt deine lokalen Commits in das Remote-Repository hoch","Erstellt einen neuen Branch"]}'::jsonb,
  2,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'git-github-remote')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'git-merge-conflicts-project',
  '{"en":"Project: Resolve a Merge Conflict","de":"Projekt: Einen Merge-Konflikt lösen"}'::jsonb,
  '[{"step":1,"text":{"en":"When two branches change the same line of the same file differently, Git can''t merge them automatically — this is called a merge conflict.","de":"Wenn zwei Branches dieselbe Zeile derselben Datei unterschiedlich ändern, kann Git sie nicht automatisch zusammenführen — das nennt man einen Merge-Konflikt."}},{"step":2,"text":{"en":"Git marks the conflict directly inside the file using <<<<<<<, =======, and >>>>>>> markers, showing both versions so a human can decide.","de":"Git markiert den Konflikt direkt in der Datei mit den Markierungen <<<<<<<, ======= und >>>>>>> und zeigt beide Versionen, damit ein Mensch entscheiden kann."}},{"step":3,"text":{"en":"To resolve it, you edit the file to keep the version you want (or combine both), delete the conflict markers completely, then git add and git commit the result.","de":"Um ihn zu lösen, bearbeitest du die Datei so, dass die gewünschte Version bleibt (oder kombinierst beide), löschst die Konfliktmarkierungen vollständig und machst dann git add und git commit."}},{"step":4,"text":{"en":"Final project: look at the conflicting versions in the starter code, write your resolved version with no markers left, and submit it.","de":"Abschlussprojekt: Sieh dir die widersprüchlichen Versionen im Startcode an, schreibe deine aufgelöste Version ohne verbleibende Markierungen und reiche sie ein."}}]'::jsonb,
  '{"js":"// Two branches both changed the SAME line of a file differently.\n// Git can''t guess which one is right, so it marks the conflict like this:\nconst fileWithConflict = `\n<h1>Welcome</h1>\n<<<<<<< HEAD\n<p>Version from main</p>\n=======\n<p>Version from feature-hero</p>\n>>>>>>> feature-hero\n`;\n\nconsole.log(fileWithConflict);\n\n// Your task: write the RESOLVED version of the file below (pick one\n// line, combine them, or write something new) with the conflict\n// markers removed, then log it.\nconst resolved = `\n<h1>Welcome</h1>\n<p>TODO: your resolved line here</p>\n`;\n\nconsole.log(\"Resolved:\", resolved);\n"}'::jsonb,
  'advanced', false, true,
  44
where not exists (select 1 from lessons where slug = 'git-merge-conflicts-project');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'git-merge-conflicts-project'),
  '{"en":"What must you do before committing a resolved merge conflict?","de":"Was musst du tun, bevor du einen gelösten Merge-Konflikt committest?"}'::jsonb,
  '{"en":["Nothing, Git resolves it automatically","Delete the whole file","Remove the conflict markers and keep only the final version you want","Create a new branch"],"de":["Nichts, Git löst es automatisch","Die ganze Datei löschen","Die Konfliktmarkierungen entfernen und nur die gewünschte finale Version behalten","Einen neuen Branch erstellen"]}'::jsonb,
  2,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'git-merge-conflicts-project')
);

