-- CodePath Academy — embedded lesson Quick Checks
-- Adds a small multiple-choice "check" to one step of every existing
-- lesson's content (LessonContentBlock.check — see src/lib/supabase/types.ts).
-- Shown inline in the lesson card itself, distinct from the separate
-- end-of-lesson quiz and the separate practice screen. Uses jsonb_set with
-- an existence guard, so safe to paste more than once.
--
-- Generated by gen-quick-checks.js — don't hand-edit, regenerate instead.

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What is a computer program, at its core?","de":"Was ist ein Computerprogramm im Kern?"},"choices":{"en":["A random collection of files","A set of exact instructions run one after another","A picture of what an app should look like"],"de":["Eine zufällige Sammlung von Dateien","Eine Folge exakter Anweisungen, die nacheinander ausgeführt werden","Ein Bild davon, wie eine App aussehen soll"]},"correctIndex":1}'::jsonb, true)
where slug = 'how-programming-works'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does the browser do with the files a server sends back?","de":"Was macht der Browser mit den Dateien, die ein Server zurücksendet?"},"choices":{"en":["Deletes them","Turns them into the page you see","Sends them to another server"],"de":["Löscht sie","Verwandelt sie in die Seite, die du siehst","Sendet sie an einen anderen Server"]},"correctIndex":1}'::jsonb, true)
where slug = 'how-websites-work'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"Which HTML tag creates a paragraph of text?","de":"Welches HTML-Tag erzeugt einen Textabsatz?"},"choices":{"en":["<h1>","<p>","<div>"],"de":["<h1>","<p>","<div>"]},"correctIndex":1}'::jsonb, true)
where slug = 'html-hello-world'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does CSS control?","de":"Was steuert CSS?"},"choices":{"en":["The structure of content","How elements look (color, size, spacing)","What a server sends back"],"de":["Die Struktur des Inhalts","Wie Elemente aussehen (Farbe, Größe, Abstand)","Was ein Server zurücksendet"]},"correctIndex":1}'::jsonb, true)
where slug = 'css-styling-basics'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does a <div> do?","de":"Was macht ein <div>?"},"choices":{"en":["Groups content together","Shows a picture","Sends a network request"],"de":["Gruppiert Inhalte zusammen","Zeigt ein Bild","Sendet eine Netzwerkanfrage"]},"correctIndex":0}'::jsonb, true)
where slug = 'html-css-div-profile-card'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Which tag is meant to hold your navigation links?","de":"Welches Tag ist für deine Navigationslinks gedacht?"},"choices":{"en":["<footer>","<nav>","<section>"],"de":["<footer>","<nav>","<section>"]},"correctIndex":1}'::jsonb, true)
where slug = 'website-structure-nav-footer'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does justify-content control in flexbox?","de":"Was steuert justify-content in Flexbox?"},"choices":{"en":["Text color","Horizontal spacing of flex items","Image size"],"de":["Textfarbe","Horizontalen Abstand der Flex-Elemente","Bildgröße"]},"correctIndex":1}'::jsonb, true)
where slug = 'flexbox-layout-basics'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does <main> mark in a page?","de":"Was markiert <main> auf einer Seite?"},"choices":{"en":["The primary content of the page","The navigation bar","A single image"],"de":["Den primären Inhalt der Seite","Die Navigationsleiste","Ein einzelnes Bild"]},"correctIndex":0}'::jsonb, true)
where slug = 'semantic-html-sections'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Which CSS property controls how bold text looks?","de":"Welche CSS-Eigenschaft steuert, wie fett Text aussieht?"},"choices":{"en":["font-family","font-weight","line-height"],"de":["font-family","font-weight","line-height"]},"correctIndex":1}'::jsonb, true)
where slug = 'typography-basics'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Where is padding, relative to an element''s border?","de":"Wo befindet sich padding relativ zum Rand (border) eines Elements?"},"choices":{"en":["Inside the border","Outside the border","It replaces the border"],"de":["Innerhalb des Rands","Außerhalb des Rands","Es ersetzt den Rand"]},"correctIndex":0}'::jsonb, true)
where slug = 'box-model-deep-dive'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What is a hero section?","de":"Was ist eine Hero-Section?"},"choices":{"en":["The footer of a page","The big eye-catching area at the top of a page","A form for user login"],"de":["Der Footer einer Seite","Der große, auffällige Bereich oben auf einer Seite","Ein Formular für den Nutzer-Login"]},"correctIndex":1}'::jsonb, true)
where slug = 'hero-section'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does a landing page typically combine?","de":"Was kombiniert eine Landingpage typischerweise?"},"choices":{"en":["Only images","Header/nav, hero, content sections, and a footer","Just a single paragraph"],"de":["Nur Bilder","Header/Nav, Hero, Inhaltsbereiche und einen Footer","Nur einen einzelnen Absatz"]},"correctIndex":1}'::jsonb, true)
where slug = 'landing-page-assembly'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does max-width: 100% do for an image?","de":"Was bewirkt max-width: 100% bei einem Bild?"},"choices":{"en":["Makes it always full screen","Stops it from overflowing its container","Removes the image"],"de":["Macht es immer bildschirmfüllend","Verhindert, dass es seinen Container überläuft","Entfernt das Bild"]},"correctIndex":1}'::jsonb, true)
where slug = 'responsive-images'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Which property turns an element into a grid container?","de":"Welche Eigenschaft macht ein Element zu einem Grid-Container?"},"choices":{"en":["display: flex","display: grid","display: block"],"de":["display: flex","display: grid","display: block"]},"correctIndex":1}'::jsonb, true)
where slug = 'css-grid-basics'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does <label> do in a form?","de":"Was macht <label> in einem Formular?"},"choices":{"en":["Collects text input","Describes what an input is for","Submits the form"],"de":["Sammelt Texteingaben","Beschreibt, wofür ein Eingabefeld ist","Sendet das Formular ab"]},"correctIndex":1}'::jsonb, true)
where slug = 'html-forms-basics'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"When does a :hover style apply?","de":"Wann gilt ein :hover-Stil?"},"choices":{"en":["Always","Only while the mouse is over the element","Only after clicking"],"de":["Immer","Nur solange die Maus über dem Element ist","Nur nach einem Klick"]},"correctIndex":1}'::jsonb, true)
where slug = 'buttons-hover-transitions'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Which three things does a complete webpage combine, per this lesson?","de":"Welche drei Dinge kombiniert eine vollständige Webseite laut dieser Lektion?"},"choices":{"en":["Structure, layout, and styling","Only images and text","Only JavaScript logic"],"de":["Struktur, Layout und Styling","Nur Bilder und Text","Nur JavaScript-Logik"]},"correctIndex":0}'::jsonb, true)
where slug = 'complete-webpage-project'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does this exam require, at minimum, besides a header and footer?","de":"Was verlangt diese Prüfung mindestens, außer Header und Footer?"},"choices":{"en":["A hero section and at least two content sections","A working login system","A database connection"],"de":["Eine Hero-Section und mindestens zwei Inhaltsbereiche","Ein funktionierendes Login-System","Eine Datenbankverbindung"]},"correctIndex":0}'::jsonb, true)
where slug = 'frontend-free-exam'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"Which layout tool does this checkpoint ask you to use for the About Me section?","de":"Welches Layout-Werkzeug sollst du laut dieser Zwischenprüfung für den „Über mich\"-Bereich nutzen?"},"choices":{"en":["CSS Grid","Flexbox","Tables"],"de":["CSS Grid","Flexbox","Tabellen"]},"correctIndex":1}'::jsonb, true)
where slug = 'html-css-checkpoint-exam'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does JavaScript add that HTML and CSS can''t?","de":"Was fügt JavaScript hinzu, was HTML und CSS nicht können?"},"choices":{"en":["Structure","Behavior — reacting to what users do","Color and spacing"],"de":["Struktur","Verhalten — reagieren auf das, was Nutzer tun","Farbe und Abstand"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-introduction'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does the let keyword do?","de":"Was macht das Schlüsselwort let?"},"choices":{"en":["Deletes a variable","Creates a variable you can use later","Runs a loop"],"de":["Löscht eine Variable","Erstellt eine Variable, die du später nutzen kannst","Führt eine Schleife aus"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-variables'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does === check?","de":"Was prüft ===?"},"choices":{"en":["If two values are exactly equal","If a variable exists","If a loop should stop"],"de":["Ob zwei Werte exakt gleich sind","Ob eine Variable existiert","Ob eine Schleife stoppen soll"]},"correctIndex":0}'::jsonb, true)
where slug = 'js-conditions'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does a for loop do?","de":"Was macht eine for-Schleife?"},"choices":{"en":["Runs code once","Repeats code a set number of times","Stores a single value"],"de":["Führt Code einmal aus","Wiederholt Code eine festgelegte Anzahl an Malen","Speichert einen einzelnen Wert"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-loops'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What is a function?","de":"Was ist eine Funktion?"},"choices":{"en":["A single stored value","A reusable block of code","A type of loop"],"de":["Ein einzelner gespeicherter Wert","Ein wiederverwendbarer Codeblock","Eine Art Schleife"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-functions'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does an array hold?","de":"Was enthält ein Array?"},"choices":{"en":["A single value","A list of values in order","A function"],"de":["Einen einzelnen Wert","Eine geordnete Liste von Werten","Eine Funktion"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-arrays'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"How does an object organize information?","de":"Wie organisiert ein Objekt Informationen?"},"choices":{"en":["In a numbered list","Using named properties","As plain text"],"de":["In einer nummerierten Liste","Mit benannten Eigenschaften","Als reiner Text"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-objects'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What is the DOM?","de":"Was ist das DOM?"},"choices":{"en":["A CSS file","The browser''s live version of your HTML","A server-side database"],"de":["Eine CSS-Datei","Die lebendige Browser-Version deines HTML","Eine serverseitige Datenbank"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-dom-basics'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"In this project, what does JavaScript do?","de":"Was macht JavaScript in diesem Projekt?"},"choices":{"en":["Creates the button''s shape","Reads what was typed and responds","Colors the background"],"de":["Erstellt die Form des Buttons","Liest das Eingetippte und reagiert darauf","Färbt den Hintergrund"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-name-greeting-project'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Why is Number() needed before adding two input values?","de":"Warum wird Number() benötigt, bevor zwei Eingabewerte addiert werden?"},"choices":{"en":["It''s not needed","Input values are text by default, and Number() converts them for math","It deletes the input"],"de":["Es wird nicht benötigt","Eingabewerte sind standardmäßig Text, Number() wandelt sie für Berechnungen um","Es löscht die Eingabe"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-calculator-project'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Which topics does this checkpoint test?","de":"Welche Themen prüft diese Zwischenprüfung?"},"choices":{"en":["Arrays and objects","Variables, conditions, loops, and functions","React components"],"de":["Arrays und Objekte","Variablen, Bedingungen, Schleifen und Funktionen","React-Komponenten"]},"correctIndex":1}'::jsonb, true)
where slug = 'js-checkpoint-exam'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does a server do with an incoming request?","de":"Was macht ein Server mit einer eingehenden Anfrage?"},"choices":{"en":["Ignores it","Processes it and sends back a response","Deletes the browser''s files"],"de":["Ignoriert sie","Verarbeitet sie und sendet eine Antwort zurück","Löscht die Dateien des Browsers"]},"correctIndex":1}'::jsonb, true)
where slug = 'what-happens-when-you-open-a-website'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What is a server, in simple terms?","de":"Was ist ein Server, einfach erklärt?"},"choices":{"en":["A physical building","A program that waits for requests and sends responses","A type of database"],"de":["Ein physisches Gebäude","Ein Programm, das auf Anfragen wartet und Antworten sendet","Eine Art Datenbank"]},"correctIndex":1}'::jsonb, true)
where slug = 'creating-your-first-server'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"In the request-response pattern, who sends the request?","de":"Wer sendet im Anfrage-Antwort-Muster die Anfrage?"},"choices":{"en":["The backend","The frontend","The database"],"de":["Das Backend","Das Frontend","Die Datenbank"]},"correctIndex":1}'::jsonb, true)
where slug = 'frontend-backend-connection'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does Node.js let you do?","de":"Was ermöglicht dir Node.js?"},"choices":{"en":["Run JavaScript on a server","Write CSS faster","Design a database"],"de":["JavaScript auf einem Server ausführen","Schneller CSS schreiben","Eine Datenbank entwerfen"]},"correctIndex":0}'::jsonb, true)
where slug = 'nodejs-introduction'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does Express help you do?","de":"Wobei hilft dir Express?"},"choices":{"en":["Style a webpage","Define server routes simply","Store passwords in plain text"],"de":["Eine Webseite stylen","Server-Routen einfach definieren","Passwörter im Klartext speichern"]},"correctIndex":1}'::jsonb, true)
where slug = 'express-routes-intro'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What format do most APIs use to send data?","de":"Welches Format nutzen die meisten APIs, um Daten zu senden?"},"choices":{"en":["JSON","CSS","HTML"],"de":["JSON","CSS","HTML"]},"correctIndex":0}'::jsonb, true)
where slug = 'building-an-api-endpoint'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What happens to information without a database?","de":"Was passiert mit Informationen ohne Datenbank?"},"choices":{"en":["It''s automatically backed up","It disappears when the program stops running","It becomes faster to access"],"de":["Sie wird automatisch gesichert","Sie verschwindet, wenn das Programm stoppt","Sie wird schneller zugänglich"]},"correctIndex":1}'::jsonb, true)
where slug = 'why-databases-exist'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What must your router function have, at minimum?","de":"Was muss deine Router-Funktion mindestens haben?"},"choices":{"en":["At least 3 routes","A working database","A CSS stylesheet"],"de":["Mindestens 3 Routen","Eine funktionierende Datenbank","Ein CSS-Stylesheet"]},"correctIndex":0}'::jsonb, true)
where slug = 'backend-free-exam'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does this checkpoint focus on?","de":"Worauf konzentriert sich diese Zwischenprüfung?"},"choices":{"en":["React hooks","Server/request fundamentals and what Node.js is","CSS animations"],"de":["React-Hooks","Server-/Anfrage-Grundlagen und was Node.js ist","CSS-Animationen"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-foundations-checkpoint-exam'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Why does a table row need an id?","de":"Warum braucht eine Tabellenzeile eine id?"},"choices":{"en":["To make it look nicer","To uniquely identify each row","To store passwords"],"de":["Damit es hübscher aussieht","Um jede Zeile eindeutig zu identifizieren","Um Passwörter zu speichern"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-database-tables'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does hashing do to a password?","de":"Was macht Hashing mit einem Passwort?"},"choices":{"en":["Encrypts it reversibly","Scrambles it into a value that can''t be reversed back","Deletes it"],"de":["Verschlüsselt es umkehrbar","Verwandelt es in einen nicht umkehrbaren Wert","Löscht es"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-password-security'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What should happen before accepting new registration data?","de":"Was sollte passieren, bevor neue Registrierungsdaten akzeptiert werden?"},"choices":{"en":["Nothing, just save it","Check that the data is valid","Email the password to the user"],"de":["Nichts, einfach speichern","Prüfen, ob die Daten gültig sind","Das Passwort per E-Mail an den Nutzer senden"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-registration-flow'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What is a session/token used for?","de":"Wofür wird eine Session/ein Token genutzt?"},"choices":{"en":["Styling the login page","Proving who you are on later requests after logging in","Storing images"],"de":["Die Login-Seite zu stylen","Zu belegen, wer du bist, bei späteren Anfragen nach dem Login","Bilder zu speichern"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-sessions-auth'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What should an API return when something goes wrong?","de":"Was sollte eine API zurückgeben, wenn etwas schiefgeht?"},"choices":{"en":["Nothing","A clear status and message","The entire database"],"de":["Nichts","Einen klaren Status und eine Nachricht","Die gesamte Datenbank"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-error-handling'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What must your login() function do?","de":"Was muss deine login()-Funktion tun?"},"choices":{"en":["Delete the user","Issue a token","Change the CSS"],"de":["Den Nutzer löschen","Ein Token ausstellen","Das CSS ändern"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-paid-exam'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Why must passwords never be stored in plain text?","de":"Warum dürfen Passwörter niemals im Klartext gespeichert werden?"},"choices":{"en":["It''s slower","Anyone with database access could read them directly","It uses more storage"],"de":["Es ist langsamer","Jeder mit Datenbankzugriff könnte sie direkt lesen","Es braucht mehr Speicherplatz"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-security-checkpoint-exam'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What are React UIs built out of?","de":"Woraus werden React-Oberflächen gebaut?"},"choices":{"en":["One giant HTML file","Small, reusable components","CSS-only blocks"],"de":["Einer riesigen HTML-Datei","Kleinen, wiederverwendbaren Komponenten","Reinen CSS-Blöcken"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-introduction'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"How do you use one component inside another?","de":"Wie nutzt du eine Komponente innerhalb einer anderen?"},"choices":{"en":["Copy its code","Write it like an HTML tag","Import it as CSS"],"de":["Ihren Code kopieren","Wie ein HTML-Tag schreiben","Als CSS importieren"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-components'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What are props used for?","de":"Wofür werden Props genutzt?"},"choices":{"en":["Styling with CSS","Passing data from a parent to a child component","Storing data in a database"],"de":["Um mit CSS zu stylen","Um Daten von einer übergeordneten an eine Kind-Komponente zu übergeben","Um Daten in einer Datenbank zu speichern"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-props'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does useState give you?","de":"Was gibt dir useState?"},"choices":{"en":["A CSS class","A value and a function to update it","A server route"],"de":["Eine CSS-Klasse","Einen Wert und eine Funktion, um ihn zu ändern","Eine Server-Route"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-state'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Which prop handles a click in React?","de":"Welche Prop behandelt einen Klick in React?"},"choices":{"en":["onHover","onClick","onLoad"],"de":["onHover","onClick","onLoad"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-events'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"Why does each list item need a unique key prop?","de":"Warum braucht jedes Listenelement eine eindeutige key-Prop?"},"choices":{"en":["To make it bold","So React can track which item changed, was added, or removed","To sort it alphabetically"],"de":["Um es fett zu machen","Damit React nachverfolgen kann, was sich geändert, hinzugefügt oder entfernt hat","Um es alphabetisch zu sortieren"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-list-rendering'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Which React concepts does this project combine?","de":"Welche React-Konzepte kombiniert dieses Projekt?"},"choices":{"en":["Only styling","Components, props, state, events, and lists","Only server routing"],"de":["Nur Styling","Komponenten, Props, State, Events und Listen","Nur Server-Routing"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-mini-project'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does useEffect''s dependency array control?","de":"Was steuert das Abhängigkeits-Array von useEffect?"},"choices":{"en":["The component''s color","When the effect re-runs","The HTML structure"],"de":["Die Farbe der Komponente","Wann der Effekt erneut läuft","Die HTML-Struktur"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-effects'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does a loading state let you show while data is being fetched?","de":"Was lässt dich ein Lade-Status anzeigen, während Daten abgerufen werden?"},"choices":{"en":["An error page","A ''Loading...'' message","The final data early"],"de":["Eine Fehlerseite","Eine „Loading...\"-Meldung","Die endgültigen Daten vorzeitig"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-fetching-data'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"In this simplified router, what decides which page is shown?","de":"Was entscheidet in diesem vereinfachten Router, welche Seite angezeigt wird?"},"choices":{"en":["The browser''s URL bar","A piece of state","A CSS file"],"de":["Die URL-Leiste des Browsers","Ein Stück State","Eine CSS-Datei"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-routing-basics'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does the Home page show while data hasn''t loaded yet?","de":"Was zeigt die Home-Seite, solange die Daten noch nicht geladen sind?"},"choices":{"en":["Nothing at all","A loading state","An error message"],"de":["Gar nichts","Einen Lade-Status","Eine Fehlermeldung"]},"correctIndex":1}'::jsonb, true)
where slug = 'react-final-project'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What can middleware do to a request?","de":"Was kann Middleware mit einer Anfrage tun?"},"choices":{"en":["Only delete it","Inspect or modify it before passing it along","Change its CSS"],"de":["Sie nur löschen","Sie prüfen oder verändern, bevor sie weitergereicht wird","Ihr CSS ändern"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-express-middleware'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does WHERE do in SQL?","de":"Was macht WHERE in SQL?"},"choices":{"en":["Chooses the table","Filters rows based on a condition","Chooses which columns to show"],"de":["Wählt die Tabelle aus","Filtert Zeilen anhand einer Bedingung","Wählt die anzuzeigenden Spalten aus"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-sql-basics'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"What does a JOIN do?","de":"Was macht ein JOIN?"},"choices":{"en":["Deletes a table","Combines matching rows from two tables","Creates a new database"],"de":["Löscht eine Tabelle","Verbindet passende Zeilen aus zwei Tabellen","Erstellt eine neue Datenbank"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-sql-joins'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{0,check}', '{"question":{"en":"Which HTTP method is used to read data?","de":"Welche HTTP-Methode wird genutzt, um Daten zu lesen?"},"choices":{"en":["POST","GET","DELETE"],"de":["POST","GET","DELETE"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-rest-api-design'
  and (content -> 0 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"What does Supabase provide?","de":"Was bietet Supabase?"},"choices":{"en":["Only a code editor","A real database and a real auth system","A CSS framework"],"de":["Nur einen Code-Editor","Eine echte Datenbank und ein echtes Auth-System","Ein CSS-Framework"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-supabase-intro'
  and (content -> 1 -> 'check') is null;

update lessons
set content = jsonb_set(content, '{1,check}', '{"question":{"en":"In this capstone, what plays the role of the database?","de":"Was übernimmt in diesem Abschlussprojekt die Rolle der Datenbank?"},"choices":{"en":["The console.log statements","The in-memory array","The HTML page"],"de":["Die console.log-Anweisungen","Das Array im Speicher","Die HTML-Seite"]},"correctIndex":1}'::jsonb, true)
where slug = 'backend-fullstack-capstone'
  and (content -> 1 -> 'check') is null;

