-- CodePath Academy — React lessons
-- Appends 7 paid-tier Frontend lessons covering React (components, props,
-- state, events, list rendering, and a mini project) right after
-- js-calculator-project (sort_order 28). Run this in the Supabase SQL editor
-- after schema.sql, seed.sql, and checkpoint_exams.sql. Safe to paste more
-- than once — every insert is guarded with "where not exists".
--
-- Generated by gen-react-lessons.js — don't hand-edit, regenerate instead.

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-introduction',
  '{"en":"React: Your First Component","de":"React: Deine erste Komponente"}'::jsonb,
  '[{"step":1,"text":{"en":"React lets you build user interfaces out of small, reusable pieces called components. Instead of writing HTML by hand, a component is a JavaScript function that returns what should appear on screen.","de":"Mit React baust du Benutzeroberflächen aus kleinen, wiederverwendbaren Teilen, sogenannten Komponenten. Statt HTML von Hand zu schreiben, ist eine Komponente eine JavaScript-Funktion, die zurückgibt, was auf dem Bildschirm erscheinen soll."}},{"step":2,"text":{"en":"The code that looks like HTML inside a JavaScript function is called JSX — it gets turned into real HTML for you automatically.","de":"Der Code, der wie HTML aussieht und in einer JavaScript-Funktion steht, heißt JSX — er wird automatisch in echtes HTML umgewandelt."}},{"step":3,"text":{"en":"Change the text inside the <h1> below and press Run to see your first component update.","de":"Ändere den Text im <h1> unten und klicke auf Ausführen, um deine erste Komponente zu aktualisieren."}}]'::jsonb,
  '{"jsx":"function App() {\n  return (\n    <div>\n      <h1>Hello, I''m learning React</h1>\n      <p>This is my first component.</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<App />);"}'::jsonb,
  'beginner', false, false,
  29
where not exists (select 1 from lessons where slug = 'react-introduction');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-introduction'),
  '{"en":"What does a React component return?","de":"Was gibt eine React-Komponente zurück?"}'::jsonb,
  '{"en":["A database connection","JSX describing what should appear on screen","A CSS file","A server response"],"de":["Eine Datenbankverbindung","JSX, das beschreibt, was auf dem Bildschirm erscheinen soll","Eine CSS-Datei","Eine Serverantwort"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-introduction')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-components',
  '{"en":"Components: Breaking the UI into Pieces","de":"Komponenten: Die Oberfläche aufteilen"}'::jsonb,
  '[{"step":1,"text":{"en":"Real apps are built from many small components, not one giant file. A component can use another component just by writing it like an HTML tag.","de":"Echte Apps bestehen aus vielen kleinen Komponenten, nicht aus einer riesigen Datei. Eine Komponente kann eine andere nutzen, indem du sie einfach wie ein HTML-Tag schreibst."}},{"step":2,"text":{"en":"Split your page into a Header component and a Profile component, then use both inside App.","de":"Teile deine Seite in eine Header-Komponente und eine Profile-Komponente auf und nutze beide innerhalb von App."}},{"step":3,"text":{"en":"This is the same \"combine\" idea from earlier lessons — small pieces, reused everywhere.","de":"Das ist dieselbe „Kombinieren\"-Idee aus früheren Lektionen — kleine Teile, überall wiederverwendet."}}]'::jsonb,
  '{"jsx":"function Header() {\n  return <h1>My Portfolio</h1>;\n}\n\nfunction Profile() {\n  return <p>Hi, I''m Ahmed. I''m learning to code.</p>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Header />\n      <Profile />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<App />);"}'::jsonb,
  'beginner', false, false,
  30
where not exists (select 1 from lessons where slug = 'react-components');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-components'),
  '{"en":"In React, how do you use one component inside another?","de":"Wie nutzt du in React eine Komponente innerhalb einer anderen?"}'::jsonb,
  '{"en":["Import it as CSS","Write it like an HTML tag, e.g. <Header />","Call it with new Header()","Copy and paste its code"],"de":["Als CSS importieren","Wie ein HTML-Tag schreiben, z. B. <Header />","Mit new Header() aufrufen","Ihren Code kopieren und einfügen"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-components')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-props',
  '{"en":"Props: Passing Data into Components","de":"Props: Daten an Komponenten übergeben"}'::jsonb,
  '[{"step":1,"text":{"en":"Components become reusable when they can receive different data. Props are how you pass data from a parent component into a child component.","de":"Komponenten werden wiederverwendbar, wenn sie unterschiedliche Daten empfangen können. Props sind der Weg, Daten von einer übergeordneten Komponente an eine Kind-Komponente zu übergeben."}},{"step":2,"text":{"en":"Give your Profile component a name prop so it can greet different people without rewriting the component.","de":"Gib deiner Profile-Komponente eine name-Prop, damit sie verschiedene Personen begrüßen kann, ohne die Komponente neu zu schreiben."}},{"step":3,"text":{"en":"Notice App can now render <Profile name=\"Ahmed\" /> and <Profile name=\"Lina\" /> using the exact same component.","de":"App kann jetzt <Profile name=\"Ahmed\" /> und <Profile name=\"Lina\" /> mit genau derselben Komponente rendern."}}]'::jsonb,
  '{"jsx":"function Profile(props) {\n  return <p>Hi, I''m {props.name}. I''m learning to code.</p>;\n}\n\nfunction App() {\n  return (\n    <div>\n      <Profile name=\"Ahmed\" />\n      <Profile name=\"Lina\" />\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<App />);"}'::jsonb,
  'beginner', false, false,
  31
where not exists (select 1 from lessons where slug = 'react-props');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-props'),
  '{"en":"What are props used for in React?","de":"Wofür werden Props in React genutzt?"}'::jsonb,
  '{"en":["Styling a component with CSS","Passing data from a parent component into a child component","Storing data in a database","Running a server"],"de":["Um eine Komponente mit CSS zu stylen","Um Daten von einer übergeordneten an eine Kind-Komponente zu übergeben","Um Daten in einer Datenbank zu speichern","Um einen Server zu betreiben"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-props')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-state',
  '{"en":"State: Components That Remember","de":"State: Komponenten, die sich erinnern"}'::jsonb,
  '[{"step":1,"text":{"en":"Props are data passed in from outside — state is data a component keeps and manages itself, using the useState hook.","de":"Props sind Daten, die von außen übergeben werden — State sind Daten, die eine Komponente selbst verwaltet, mit dem useState-Hook."}},{"step":2,"text":{"en":"useState gives you a value and a function to update it. When you update it, React automatically re-renders the component with the new value.","de":"useState gibt dir einen Wert und eine Funktion, um ihn zu ändern. Wenn du ihn änderst, rendert React die Komponente automatisch mit dem neuen Wert neu."}},{"step":3,"text":{"en":"Click the button below — the count is stored in state, so React redraws the number every time it changes.","de":"Klicke auf den Button unten — die Zahl wird im State gespeichert, React zeichnet sie bei jeder Änderung neu."}}]'::jsonb,
  '{"jsx":"function Counter() {\n  const [count, setCount] = React.useState(0);\n\n  return (\n    <div>\n      <h1>Count: {count}</h1>\n      <button onClick={() => setCount(count + 1)}>Add one</button>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<Counter />);"}'::jsonb,
  'beginner', false, false,
  32
where not exists (select 1 from lessons where slug = 'react-state');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-state'),
  '{"en":"What does calling setCount(count + 1) do?","de":"Was macht der Aufruf setCount(count + 1)?"}'::jsonb,
  '{"en":["Deletes the counter","Updates the state and tells React to re-render","Sends data to a server","Changes the CSS of the button"],"de":["Löscht den Zähler","Aktualisiert den State und lässt React neu rendern","Sendet Daten an einen Server","Ändert das CSS des Buttons"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-state')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-events',
  '{"en":"Handling User Input","de":"Nutzereingaben verarbeiten"}'::jsonb,
  '[{"step":1,"text":{"en":"Real apps react to what the user does — typing, clicking, submitting. In React, you handle these with event props like onClick and onChange.","de":"Echte Apps reagieren auf das, was Nutzer tun — tippen, klicken, absenden. In React handhabst du das mit Event-Props wie onClick und onChange."}},{"step":2,"text":{"en":"Build a small input box that updates state as the user types, and shows the current value live on the page.","de":"Baue ein kleines Eingabefeld, das den State aktualisiert, während getippt wird, und zeigt den aktuellen Wert live auf der Seite."}},{"step":3,"text":{"en":"This is the same pattern every form in this course will use: state holds the value, an event handler updates it.","de":"Das ist das gleiche Muster, das jedes Formular in diesem Kurs nutzt: State hält den Wert, ein Event-Handler aktualisiert ihn."}}]'::jsonb,
  '{"jsx":"function NameInput() {\n  const [name, setName] = React.useState(\"\");\n\n  return (\n    <div>\n      <input\n        value={name}\n        onChange={(e) => setName(e.target.value)}\n        placeholder=\"Type your name\"\n      />\n      <p>Hello, {name || \"stranger\"}!</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<NameInput />);"}'::jsonb,
  'beginner', false, false,
  33
where not exists (select 1 from lessons where slug = 'react-events');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-events'),
  '{"en":"Which prop do you use to react to text being typed into an <input>?","de":"Welche Prop nutzt du, um auf getippten Text in einem <input> zu reagieren?"}'::jsonb,
  '{"en":["onClick","onType","onChange","onSubmitText"],"de":["onClick","onType","onChange","onSubmitText"]}'::jsonb,
  2,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-events')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-list-rendering',
  '{"en":"Rendering Lists","de":"Listen rendern"}'::jsonb,
  '[{"step":1,"text":{"en":"Apps rarely show just one item — they show lists: posts, products, tasks. In React you use the array''s .map() method to turn data into components.","de":"Apps zeigen selten nur ein Element — sie zeigen Listen: Beiträge, Produkte, Aufgaben. In React nutzt du die Array-Methode .map(), um Daten in Komponenten umzuwandeln."}},{"step":2,"text":{"en":"Every item in a list needs a unique key prop, so React can track which item is which when the list changes.","de":"Jedes Element in einer Liste braucht eine eindeutige key-Prop, damit React nachverfolgen kann, welches Element sich geändert hat, wenn sich die Liste ändert."}},{"step":3,"text":{"en":"Turn the tasks array below into a list of <li> elements using .map().","de":"Verwandle das tasks-Array unten mit .map() in eine Liste von <li>-Elementen."}}]'::jsonb,
  '{"jsx":"function TaskList() {\n  const tasks = [\"Learn HTML\", \"Learn CSS\", \"Learn JavaScript\", \"Learn React\"];\n\n  return (\n    <ul>\n      {tasks.map((task, index) => (\n        <li key={index}>{task}</li>\n      ))}\n    </ul>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<TaskList />);"}'::jsonb,
  'beginner', false, false,
  34
where not exists (select 1 from lessons where slug = 'react-list-rendering');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-list-rendering'),
  '{"en":"Why does each item in a rendered list need a unique key prop?","de":"Warum braucht jedes Element einer gerenderten Liste eine eindeutige key-Prop?"}'::jsonb,
  '{"en":["It makes the text bold","It''s required by CSS","It helps React track which item changed, was added, or removed","It sorts the list alphabetically"],"de":["Es macht den Text fett","CSS verlangt es","Es hilft React nachzuverfolgen, welches Element geändert, hinzugefügt oder entfernt wurde","Es sortiert die Liste alphabetisch"]}'::jsonb,
  2,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-list-rendering')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-mini-project',
  '{"en":"Project: Task Tracker","de":"Projekt: Aufgaben-Tracker"}'::jsonb,
  '[{"step":1,"text":{"en":"Time to combine everything: components, props, state, events, and list rendering — in one small real app.","de":"Zeit, alles zu kombinieren: Komponenten, Props, State, Events und Listen-Rendering — in einer kleinen echten App."}},{"step":2,"text":{"en":"Build a task tracker: an input + button to add a new task, and a list that renders every task using state and .map().","de":"Baue einen Aufgaben-Tracker: ein Eingabefeld mit Button, um eine neue Aufgabe hinzuzufügen, und eine Liste, die jede Aufgabe mit State und .map() rendert."}},{"step":3,"text":{"en":"When it works the way you want, submit it to your portfolio below.","de":"Wenn es so funktioniert, wie du willst, reiche es unten in dein Portfolio ein."}}]'::jsonb,
  '{"jsx":"function TaskTracker() {\n  const [tasks, setTasks] = React.useState([\"Learn React\"]);\n  const [text, setText] = React.useState(\"\");\n\n  function addTask() {\n    if (text.trim() === \"\") return;\n    setTasks([...tasks, text]);\n    setText(\"\");\n  }\n\n  return (\n    <div>\n      <h1>My Tasks</h1>\n      <input value={text} onChange={(e) => setText(e.target.value)} placeholder=\"New task\" />\n      <button onClick={addTask}>Add</button>\n      <ul>\n        {tasks.map((task, index) => (\n          <li key={index}>{task}</li>\n        ))}\n      </ul>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<TaskTracker />);"}'::jsonb,
  'intermediate', false, true,
  35
where not exists (select 1 from lessons where slug = 'react-mini-project');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-mini-project'),
  '{"en":"In the task tracker, why do we use [...tasks, text] instead of tasks.push(text)?","de":"Warum nutzen wir im Aufgaben-Tracker [...tasks, text] statt tasks.push(text)?"}'::jsonb,
  '{"en":["push() doesn''t exist in JavaScript","React needs a brand new array so it notices the state changed","[...tasks, text] is faster to type","It converts the array to a string"],"de":["push() gibt es in JavaScript nicht","React braucht ein komplett neues Array, um die State-Änderung zu bemerken","[...tasks, text] ist schneller zu tippen","Es wandelt das Array in einen String um"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-mini-project')
);

