-- CodePath Academy — React hooks/routing lessons
-- Appends 4 more paid-tier Frontend lessons (useEffect, simulated data
-- fetching, state-based routing, and a capstone mini dashboard project)
-- right after react-mini-project (sort_order 35). Completes the PRD's named
-- React scope: components, props, state, hooks, routing, API. Run this in
-- the Supabase SQL editor after react_lessons.sql. Safe to paste more than
-- once — every insert is guarded with "where not exists".
--
-- Generated by gen-react-hooks-lessons.js — don't hand-edit, regenerate instead.

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-effects',
  '{"en":"Effects: Running Code After Render","de":"Effekte: Code nach dem Rendern ausführen"}'::jsonb,
  '[{"step":1,"text":{"en":"Some things need to happen after a component renders and keep happening on their own — like a clock ticking forward every second. The useEffect hook lets you run this kind of code as a side effect of rendering.","de":"Manche Dinge müssen nach dem Rendern passieren und von selbst weiterlaufen — wie eine Uhr, die jede Sekunde weitertickt. Der useEffect-Hook lässt dich solchen Code als Seiteneffekt des Renderns ausführen."}},{"step":2,"text":{"en":"useEffect takes a function to run, and a dependency array that controls when it re-runs. An empty array [] means \"run once, when the component first appears\" — perfect for starting a timer.","de":"useEffect nimmt eine Funktion, die ausgeführt wird, und ein Abhängigkeits-Array, das steuert, wann sie erneut läuft. Ein leeres Array [] bedeutet „einmal ausführen, wenn die Komponente zum ersten Mal erscheint\" — perfekt, um einen Timer zu starten."}},{"step":3,"text":{"en":"Notice the function returned inside useEffect: it''s a cleanup function React calls when the component is removed, so the timer doesn''t keep running forever.","de":"Beachte die Funktion, die useEffect zurückgibt: Das ist eine Cleanup-Funktion, die React aufruft, wenn die Komponente entfernt wird, damit der Timer nicht für immer weiterläuft."}}]'::jsonb,
  '{"jsx":"function Clock() {\n  const [seconds, setSeconds] = React.useState(0);\n\n  React.useEffect(() => {\n    const timer = setInterval(() => {\n      setSeconds((s) => s + 1);\n    }, 1000);\n    return () => clearInterval(timer);\n  }, []);\n\n  return <h1>Seconds elapsed: {seconds}</h1>;\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<Clock />);"}'::jsonb,
  'intermediate', false, false,
  36
where not exists (select 1 from lessons where slug = 'react-effects');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-effects'),
  '{"en":"Why does useEffect return a function in the clock example?","de":"Warum gibt useEffect im Uhr-Beispiel eine Funktion zurück?"}'::jsonb,
  '{"en":["To make the code run faster","To clean up the timer so it stops when the component is removed","To send data to a server","To style the h1 element"],"de":["Um den Code schneller zu machen","Um den Timer aufzuräumen, damit er stoppt, wenn die Komponente entfernt wird","Um Daten an einen Server zu senden","Um das h1-Element zu stylen"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-effects')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-fetching-data',
  '{"en":"Fetching Data","de":"Daten abrufen"}'::jsonb,
  '[{"step":1,"text":{"en":"Real apps load data from a server instead of hardcoding it. fetchUser() below simulates that with a Promise and a short delay — the same shape as a real fetch() call to an API.","de":"Echte Apps laden Daten von einem Server, statt sie fest einzucodieren. fetchUser() simuliert das unten mit einem Promise und einer kurzen Verzögerung — genau wie ein echter fetch()-Aufruf an eine API."}},{"step":2,"text":{"en":"While the data is loading, the component shows \"Loading...\" — this loading state is a pattern you''ll use in almost every real app.","de":"Während die Daten laden, zeigt die Komponente „Loading...\" — dieses Lade-Muster nutzt du in fast jeder echten App."}},{"step":3,"text":{"en":"Once the promise resolves, setUser and setLoading update state, and React re-renders with the real data.","de":"Sobald das Promise aufgelöst ist, aktualisieren setUser und setLoading den State, und React rendert mit den echten Daten neu."}}]'::jsonb,
  '{"jsx":"function UserProfile() {\n  const [user, setUser] = React.useState(null);\n  const [loading, setLoading] = React.useState(true);\n\n  function fetchUser() {\n    return new Promise((resolve) => {\n      setTimeout(() => resolve({ name: \"Ahmed\", role: \"Student\" }), 1000);\n    });\n  }\n\n  React.useEffect(() => {\n    fetchUser().then((data) => {\n      setUser(data);\n      setLoading(false);\n    });\n  }, []);\n\n  if (loading) return <p>Loading...</p>;\n\n  return (\n    <div>\n      <h1>{user.name}</h1>\n      <p>{user.role}</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<UserProfile />);"}'::jsonb,
  'intermediate', false, false,
  37
where not exists (select 1 from lessons where slug = 'react-fetching-data');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-fetching-data'),
  '{"en":"Why does the component check loading before rendering the user''s data?","de":"Warum prüft die Komponente loading, bevor sie die Nutzerdaten anzeigt?"}'::jsonb,
  '{"en":["Because user is not available yet while the data is being fetched","Because loading is required by React","To make the component run faster","Because fetch() cannot be used with useState"],"de":["Weil user während des Ladens noch nicht verfügbar ist","Weil loading von React verlangt wird","Um die Komponente schneller zu machen","Weil fetch() nicht mit useState genutzt werden kann"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-fetching-data')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-routing-basics',
  '{"en":"Routing: Multiple Pages in One App","de":"Routing: Mehrere Seiten in einer App"}'::jsonb,
  '[{"step":1,"text":{"en":"Real apps have multiple pages — Home, About, Profile. In a full setup you''d use a router library, but the core idea is simple: keep track of which \"page\" is active in state, and render different content for each.","de":"Echte Apps haben mehrere Seiten — Home, About, Profil. In einem vollständigen Setup würdest du eine Router-Bibliothek nutzen, aber die Grundidee ist einfach: merke dir im State, welche „Seite\" gerade aktiv ist, und rendere für jede unterschiedlichen Inhalt."}},{"step":2,"text":{"en":"This simulated router shows how real routing works underneath: one variable decides what''s on screen, and clicking a link just changes that variable.","de":"Dieser simulierte Router zeigt, wie echtes Routing im Kern funktioniert: eine Variable entscheidet, was auf dem Bildschirm ist, und ein Klick auf einen Link ändert einfach diese Variable."}},{"step":3,"text":{"en":"Try switching between Home and About using the buttons below.","de":"Probiere, mit den Buttons unten zwischen Home und About zu wechseln."}}]'::jsonb,
  '{"jsx":"function App() {\n  const [page, setPage] = React.useState(\"home\");\n\n  return (\n    <div>\n      <nav>\n        <button onClick={() => setPage(\"home\")}>Home</button>\n        <button onClick={() => setPage(\"about\")}>About</button>\n      </nav>\n      {page === \"home\" && <h1>Welcome home!</h1>}\n      {page === \"about\" && <h1>About this app</h1>}\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<App />);"}'::jsonb,
  'intermediate', false, false,
  38
where not exists (select 1 from lessons where slug = 'react-routing-basics');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-routing-basics'),
  '{"en":"In this simplified router, what actually decides which page is shown?","de":"Was entscheidet in diesem vereinfachten Router tatsächlich, welche Seite angezeigt wird?"}'::jsonb,
  '{"en":["The browser''s URL bar","A piece of state that tracks the current page","A separate HTML file for each page","The order of the buttons"],"de":["Die URL-Leiste des Browsers","Ein Stück State, das die aktuelle Seite verfolgt","Eine separate HTML-Datei pro Seite","Die Reihenfolge der Buttons"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-routing-basics')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'react-final-project',
  '{"en":"Project: Mini Dashboard","de":"Projekt: Mini-Dashboard"}'::jsonb,
  '[{"step":1,"text":{"en":"Final React project: combine components, props, state, events, lists, effects, simulated data fetching, and simple routing into one small dashboard app.","de":"Letztes React-Projekt: Kombiniere Komponenten, Props, State, Events, Listen, Effekte, simuliertes Datenabrufen und einfaches Routing in einer kleinen Dashboard-App."}},{"step":2,"text":{"en":"Build a two-page app: a Home page showing a loading-then-loaded list of items (simulated fetch), and a Stats page showing a simple count. Use the state-based router pattern from the last lesson.","de":"Baue eine App mit zwei Seiten: eine Home-Seite, die eine erst ladende, dann geladene Liste von Elementen zeigt (simulierter Abruf), und eine Stats-Seite mit einer einfachen Zählung. Nutze das State-basierte Router-Muster aus der letzten Lektion."}},{"step":3,"text":{"en":"When you''re happy with it, submit it to your portfolio.","de":"Wenn du zufrieden bist, reiche es in dein Portfolio ein."}}]'::jsonb,
  '{"jsx":"function Dashboard() {\n  const [page, setPage] = React.useState(\"home\");\n  const [items, setItems] = React.useState([]);\n  const [loading, setLoading] = React.useState(true);\n\n  React.useEffect(() => {\n    setTimeout(() => {\n      setItems([\"Task 1\", \"Task 2\", \"Task 3\"]);\n      setLoading(false);\n    }, 800);\n  }, []);\n\n  return (\n    <div>\n      <nav>\n        <button onClick={() => setPage(\"home\")}>Home</button>\n        <button onClick={() => setPage(\"stats\")}>Stats</button>\n      </nav>\n\n      {page === \"home\" && (\n        <div>\n          <h1>Your Items</h1>\n          {loading ? (\n            <p>Loading...</p>\n          ) : (\n            <ul>\n              {items.map((item, i) => (\n                <li key={i}>{item}</li>\n              ))}\n            </ul>\n          )}\n        </div>\n      )}\n\n      {page === \"stats\" && <h1>You have {items.length} items</h1>}\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(<Dashboard />);"}'::jsonb,
  'advanced', false, true,
  39
where not exists (select 1 from lessons where slug = 'react-final-project');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'react-final-project'),
  '{"en":"What combination of React concepts does this dashboard use?","de":"Welche Kombination von React-Konzepten nutzt dieses Dashboard?"}'::jsonb,
  '{"en":["Only CSS animations","State, effects, simulated fetching, lists, and a state-based router — all together","A real backend server","Only HTML forms"],"de":["Nur CSS-Animationen","State, Effekte, simuliertes Abrufen, Listen und einen State-basierten Router — alles zusammen","Einen echten Backend-Server","Nur HTML-Formulare"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'react-final-project')
);

