-- CodePath Academy — Automated Testing unit
-- Appends 5 more paid-tier Frontend lessons (testing-why-write-tests
-- through testing-final-project, sort_order 51-55, right after
-- ts-final-project at 50). Third item off the "not a full course yet" gap
-- list. No real test runner (Jest etc.) exists in the sandbox, so every
-- lesson's starter code includes a tiny hand-written test(name, fn) +
-- expect(actual).toBe(expected) harness — a real, working, if minimal,
-- implementation of the same idea bigger tools scale up, not a fake
-- simulation, so students genuinely run tests and see PASS/FAIL. Safe to
-- paste more than once — every insert is guarded with "where not exists".
--
-- Generated by gen-testing-lessons.js — don't hand-edit, regenerate instead.

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'testing-why-write-tests',
  '{"en":"Why Write Automated Tests?","de":"Warum automatisierte Tests schreiben?"}'::jsonb,
  '[{"step":1,"text":{"en":"So far, checking your code meant running it and reading the output yourself. That works for a tiny script, but real projects have hundreds of functions — re-checking everything by hand after every change doesn''t scale.","de":"Bisher hast du deinen Code überprüft, indem du ihn ausgeführt und die Ausgabe selbst gelesen hast. Das funktioniert für ein kleines Skript, aber echte Projekte haben Hunderte von Funktionen — nach jeder Änderung alles von Hand zu prüfen, skaliert nicht."}},{"step":2,"text":{"en":"An automated test is code that checks other code for you: it runs a function, compares the result to what you expected, and tells you PASS or FAIL — automatically, every time, for free.","de":"Ein automatisierter Test ist Code, der anderen Code für dich prüft: Er führt eine Funktion aus, vergleicht das Ergebnis mit dem, was du erwartet hast, und sagt dir automatisch, bei jedem Mal, kostenlos: PASS oder FAIL."}},{"step":3,"text":{"en":"The real payoff shows up later: months from now, when you change addTax and accidentally break it, a test catches that instantly — instead of a real user noticing a wrong price.","de":"Der eigentliche Gewinn zeigt sich später: Wenn du addTax Monate später änderst und dabei versehentlich kaputt machst, erkennt ein Test das sofort — statt dass ein echter Nutzer einen falschen Preis bemerkt."}}]'::jsonb,
  '{"js":"function addTax(price) {\n  return price * 1.19;\n}\n\n// Right now, the only way to check this works is to run it and\n// read the number yourself, every single time you change the code.\nconsole.log(addTax(100));\n"}'::jsonb,
  'beginner', false, false,
  51
where not exists (select 1 from lessons where slug = 'testing-why-write-tests');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'testing-why-write-tests'),
  '{"en":"What is the main problem with only checking code by reading console output yourself?","de":"Was ist das Hauptproblem, wenn man Code nur durch selbst gelesene Konsolenausgaben prüft?"}'::jsonb,
  '{"en":["It''s illegal","It doesn''t scale — you can''t realistically re-check everything by hand after every change","The console can''t show numbers","It only works for CSS"],"de":["Es ist verboten","Es skaliert nicht — man kann nicht realistisch alles von Hand nach jeder Änderung neu prüfen","Die Konsole kann keine Zahlen anzeigen","Es funktioniert nur für CSS"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'testing-why-write-tests')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'testing-your-first-test',
  '{"en":"Your First Test","de":"Dein erster Test"}'::jsonb,
  '[{"step":1,"text":{"en":"The starter code includes a tiny hand-built test harness — a real, working (if small) version of what tools like Jest do at a much bigger scale: an expect() that compares values, and a test() that runs and labels a check.","de":"Der Startcode enthält ein kleines, selbst gebautes Test-Framework — eine echte, wenn auch kleine Version dessen, was Tools wie Jest in viel größerem Maßstab tun: ein expect(), das Werte vergleicht, und ein test(), das eine Prüfung ausführt und benennt."}},{"step":2,"text":{"en":"test(\"description\", () => { ... }) names what you''re checking and runs the function inside it. expect(actual).toBe(expected) is the actual comparison — it logs PASS or FAIL to the console.","de":"test(\"beschreibung\", () => { ... }) benennt, was du prüfst, und führt die Funktion darin aus. expect(actual).toBe(expected) ist der eigentliche Vergleich — er gibt PASS oder FAIL in der Konsole aus."}},{"step":3,"text":{"en":"Add a second test for add(-1, 1) below the first one, run it, and confirm you see PASS for both.","de":"Füge unter dem ersten einen zweiten Test für add(-1, 1) hinzu, führe ihn aus und bestätige, dass du bei beiden PASS siehst."}}]'::jsonb,
  '{"js":"function expect(actual) {\n  return {\n    toBe(expected) {\n      if (actual === expected) {\n        console.log(\"PASS: expected \" + actual + \" to be \" + expected);\n      } else {\n        console.log(\"FAIL: expected \" + expected + \" but got \" + actual);\n      }\n    },\n  };\n}\n\nfunction test(name, fn) {\n  console.log(\"Test: \" + name);\n  fn();\n}\n\nfunction add(a, b) {\n  return a + b;\n}\n\ntest(\"add(2, 3) should be 5\", () => {\n  expect(add(2, 3)).toBe(5);\n});\n\n// Try it: add a second test below for add(-1, 1).\n"}'::jsonb,
  'beginner', false, false,
  52
where not exists (select 1 from lessons where slug = 'testing-your-first-test');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'testing-your-first-test'),
  '{"en":"In `expect(add(2, 3)).toBe(5)`, what is being compared?","de":"Was wird bei `expect(add(2, 3)).toBe(5)` verglichen?"}'::jsonb,
  '{"en":["The result of add(2, 3) against the expected value 5","Two random numbers","The word \"add\" against the word \"toBe\"","Nothing, it just prints text"],"de":["Das Ergebnis von add(2, 3) gegen den erwarteten Wert 5","Zwei zufällige Zahlen","Das Wort \"add\" gegen das Wort \"toBe\"","Nichts, es gibt nur Text aus"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'testing-your-first-test')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'testing-edge-cases',
  '{"en":"Testing Edge Cases, Not Just the Obvious Input","de":"Grenzfälle testen, nicht nur den offensichtlichen Fall"}'::jsonb,
  '[{"step":1,"text":{"en":"It''s tempting to only test the input that obviously works — but real bugs almost always hide in the cases you didn''t think to check: zero, negative numbers, empty lists, missing values.","de":"Es ist verlockend, nur den Fall zu testen, der offensichtlich funktioniert — aber echte Bugs verstecken sich fast immer in den Fällen, an die man nicht gedacht hat: null, negative Zahlen, leere Listen, fehlende Werte."}},{"step":2,"text":{"en":"These are called edge cases — the unusual, boundary, or extreme inputs a function might actually receive in the real world, even if they weren''t what you had in mind while writing it.","de":"Man nennt sie Grenzfälle (edge cases) — die ungewöhnlichen, extremen Eingaben, die eine Funktion in der echten Welt tatsächlich bekommen kann, auch wenn du beim Schreiben nicht daran gedacht hast."}},{"step":3,"text":{"en":"Run the starter code: dividing by zero doesn''t crash in JavaScript, it returns Infinity — a genuinely useful thing to know and confirm with a test, not just assume.","de":"Führe den Startcode aus: Division durch null führt in JavaScript nicht zum Absturz, sondern ergibt Infinity — gut zu wissen und mit einem Test zu bestätigen, statt es nur anzunehmen."}}]'::jsonb,
  '{"js":"function expect(actual) {\n  return {\n    toBe(expected) {\n      if (actual === expected) {\n        console.log(\"PASS: expected \" + actual + \" to be \" + expected);\n      } else {\n        console.log(\"FAIL: expected \" + expected + \" but got \" + actual);\n      }\n    },\n  };\n}\n\nfunction test(name, fn) {\n  console.log(\"Test: \" + name);\n  fn();\n}\n\nfunction divide(a, b) {\n  return a / b;\n}\n\ntest(\"divide(10, 2) should be 5\", () => {\n  expect(divide(10, 2)).toBe(5);\n});\n\n// The \"obvious\" case works. But what about the edge cases?\ntest(\"divide(5, 0) should be Infinity\", () => {\n  expect(divide(5, 0)).toBe(Infinity);\n});\n"}'::jsonb,
  'intermediate', false, false,
  53
where not exists (select 1 from lessons where slug = 'testing-edge-cases');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'testing-edge-cases'),
  '{"en":"Why bother testing edge cases like dividing by zero or an empty list?","de":"Warum sollte man Grenzfälle wie Division durch null oder eine leere Liste testen?"}'::jsonb,
  '{"en":["To make the test file longer","Because real bugs usually hide in unusual inputs, not the obvious happy-path case","Edge cases are required by the browser","It makes the code run faster"],"de":["Um die Testdatei länger zu machen","Weil sich echte Bugs meist in ungewöhnlichen Eingaben verstecken, nicht im offensichtlichen Normalfall","Grenzfälle sind vom Browser vorgeschrieben","Es macht den Code schneller"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'testing-edge-cases')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'testing-catches-a-real-bug',
  '{"en":"Watching a Test Catch a Real Bug","de":"Wie ein Test einen echten Bug findet"}'::jsonb,
  '[{"step":1,"text":{"en":"This is the real loop of test-driven work: run the test, read the FAIL message, fix the code, run again, see PASS. Every professional developer does this dozens of times a day.","de":"Das ist der eigentliche Kreislauf testgetriebener Arbeit: Test ausführen, die FAIL-Meldung lesen, den Code korrigieren, erneut ausführen, PASS sehen. Jeder professionelle Entwickler macht das mehrmals täglich."}},{"step":2,"text":{"en":"Run the starter code as-is first. Read the FAIL message carefully — it tells you exactly what was expected versus what actually happened, which is usually enough to spot the bug.","de":"Führe den Startcode zuerst unverändert aus. Lies die FAIL-Meldung genau — sie sagt dir genau, was erwartet wurde und was tatsächlich passiert ist, was meist reicht, um den Bug zu finden."}},{"step":3,"text":{"en":"isEven currently checks for odd numbers (n % 2 === 1) instead of even ones. Fix the comparison so it correctly returns true for even numbers, then re-run and confirm PASS.","de":"isEven prüft aktuell auf ungerade Zahlen (n % 2 === 1) statt auf gerade. Korrigiere den Vergleich, sodass er für gerade Zahlen korrekt true zurückgibt, führe dann erneut aus und bestätige PASS."}}]'::jsonb,
  '{"js":"function expect(actual) {\n  return {\n    toBe(expected) {\n      if (actual === expected) {\n        console.log(\"PASS: expected \" + actual + \" to be \" + expected);\n      } else {\n        console.log(\"FAIL: expected \" + expected + \" but got \" + actual);\n      }\n    },\n  };\n}\n\nfunction test(name, fn) {\n  console.log(\"Test: \" + name);\n  fn();\n}\n\n// This function has a bug in it.\nfunction isEven(n) {\n  return n % 2 === 1;\n}\n\ntest(\"isEven(4) should be true\", () => {\n  expect(isEven(4)).toBe(true);\n});\n\n// Run it — the test fails, and tells you exactly what went wrong.\n// Fix isEven above so the test passes, then run again.\n"}'::jsonb,
  'intermediate', false, false,
  54
where not exists (select 1 from lessons where slug = 'testing-catches-a-real-bug');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'testing-catches-a-real-bug'),
  '{"en":"What''s the normal workflow when a test fails?","de":"Was ist der normale Ablauf, wenn ein Test fehlschlägt?"}'::jsonb,
  '{"en":["Delete the test so it stops failing","Read the failure message, fix the actual code, then re-run the test","Ignore it and move on","Rewrite the whole file from scratch"],"de":["Den Test löschen, damit er nicht mehr fehlschlägt","Die Fehlermeldung lesen, den eigentlichen Code korrigieren, dann den Test erneut ausführen","Ignorieren und weitermachen","Die ganze Datei neu schreiben"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'testing-catches-a-real-bug')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'testing-final-project',
  '{"en":"Project: Write a Small Test Suite","de":"Projekt: Eine kleine Testsuite schreiben"}'::jsonb,
  '[{"step":1,"text":{"en":"Final project: write a small but real test suite — a set of tests covering more than one function, including at least one edge case, exactly like a professional would before shipping this code.","de":"Abschlussprojekt: Schreibe eine kleine, aber echte Testsuite — mehrere Tests, die mehr als eine Funktion abdecken, inklusive mindestens einem Grenzfall, genau wie ein Profi es vor der Veröffentlichung dieses Codes tun würde."}},{"step":2,"text":{"en":"cartTotal and applyDiscount are the same style of functions from earlier in the course — now you''re testing them instead of just calling them once and eyeballing the result.","de":"cartTotal und applyDiscount sind Funktionen im selben Stil wie zuvor im Kurs — jetzt testest du sie, statt sie nur einmal aufzurufen und das Ergebnis mit dem Auge zu prüfen."}},{"step":3,"text":{"en":"Add at least 3 more tests, including one edge case (an empty cart array, or a 0% discount that should leave the total unchanged), then submit your finished file to your portfolio.","de":"Füge mindestens 3 weitere Tests hinzu, darunter einen Grenzfall (ein leeres Warenkorb-Array oder ein 0%-Rabatt, der die Summe unverändert lassen sollte), und reiche deine fertige Datei dann in dein Portfolio ein."}}]'::jsonb,
  '{"js":"function expect(actual) {\n  return {\n    toBe(expected) {\n      if (actual === expected) {\n        console.log(\"PASS: expected \" + actual + \" to be \" + expected);\n      } else {\n        console.log(\"FAIL: expected \" + expected + \" but got \" + actual);\n      }\n    },\n  };\n}\n\nfunction test(name, fn) {\n  console.log(\"Test: \" + name);\n  fn();\n}\n\nfunction cartTotal(items) {\n  return items.reduce((sum, item) => sum + item.price * item.quantity, 0);\n}\n\nfunction applyDiscount(total, percent) {\n  return total - (total * percent) / 100;\n}\n\n// Example test to get you started:\ntest(\"cartTotal of one item\", () => {\n  expect(cartTotal([{ price: 10, quantity: 2 }])).toBe(20);\n});\n\n// Your task: add at least 3 more tests covering cartTotal and\n// applyDiscount, including at least one edge case (an empty cart,\n// or a 0% discount).\n"}'::jsonb,
  'advanced', false, true,
  55
where not exists (select 1 from lessons where slug = 'testing-final-project');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'testing-final-project'),
  '{"en":"Besides the normal case, what should a good test suite for cartTotal include?","de":"Was sollte eine gute Testsuite für cartTotal neben dem Normalfall enthalten?"}'::jsonb,
  '{"en":["Nothing else, one test is always enough","At least one edge case, like an empty cart","A CSS test","A screenshot"],"de":["Nichts weiter, ein Test reicht immer","Mindestens einen Grenzfall, wie einen leeren Warenkorb","Einen CSS-Test","Einen Screenshot"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'testing-final-project')
);

