-- CodePath Academy — TypeScript unit
-- Appends 6 more paid-tier Frontend lessons (ts-what-is-typescript through
-- ts-final-project, sort_order 45-50, right after git-merge-conflicts-project
-- at 44). TypeScript was a completely missing topic despite being used in
-- nearly every real React job today. Requires two small platform additions
-- alongside this content: StarterCode gained a `ts` field and CodeWorkspace
-- gained a "ts" editor tab that Babel Standalone transpiles client-side via
-- the "typescript" preset (same no-build-step technique already used for
-- JSX) — see src/components/learn/CodeWorkspace.tsx. The JSX tab's Babel
-- presets were also widened to "react,typescript" so a lesson can write
-- typed React props directly (ts-typed-react-props), without a separate
-- .tsx language tab. Safe to paste more than once — every insert is
-- guarded with "where not exists".
--
-- Generated by gen-ts-lessons.js — don't hand-edit, regenerate instead.

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'ts-what-is-typescript',
  '{"en":"What Is TypeScript?","de":"Was ist TypeScript?"}'::jsonb,
  '[{"step":1,"text":{"en":"TypeScript is JavaScript with an extra layer on top: types. You write almost the same code you already know, but you can describe what kind of value each variable is meant to hold.","de":"TypeScript ist JavaScript mit einer zusätzlichen Ebene: Typen. Du schreibst fast denselben Code, den du schon kennst, kannst aber beschreiben, welche Art von Wert eine Variable enthalten soll."}},{"step":2,"text":{"en":"The browser can''t run TypeScript directly. A tool (here, Babel) strips the type annotations before running, turning your TypeScript into plain JavaScript underneath.","de":"Der Browser kann TypeScript nicht direkt ausführen. Ein Tool (hier Babel) entfernt die Typangaben vor der Ausführung und macht aus deinem TypeScript darunter reines JavaScript."}},{"step":3,"text":{"en":"The real benefit isn''t at runtime — it''s while you''re writing code. Your type checker catches mistakes immediately, before you ever click Run, instead of you discovering them later as a bug.","de":"Der eigentliche Vorteil liegt nicht zur Laufzeit — sondern beim Schreiben des Codes. Deine Typprüfung erkennt Fehler sofort, bevor du überhaupt auf Ausführen klickst, statt dass du sie später als Bug entdeckst."}}]'::jsonb,
  '{"ts":"// TypeScript adds types on top of JavaScript.\n// This line has a type annotation: \": string\"\nlet greeting: string = \"Hello, TypeScript!\";\nconsole.log(greeting);\n\ngreeting = \"Still a string\";\nconsole.log(greeting);\n"}'::jsonb,
  'beginner', false, false,
  45
where not exists (select 1 from lessons where slug = 'ts-what-is-typescript');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'ts-what-is-typescript'),
  '{"en":"What does TypeScript actually add on top of JavaScript?","de":"Was fügt TypeScript eigentlich zu JavaScript hinzu?"}'::jsonb,
  '{"en":["A completely different language","Optional type annotations that are checked before running","A faster way to run code","A new way to write HTML"],"de":["Eine komplett andere Sprache","Optionale Typangaben, die vor der Ausführung geprüft werden","Eine schnellere Art, Code auszuführen","Eine neue Art, HTML zu schreiben"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'ts-what-is-typescript')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'ts-basic-types',
  '{"en":"Basic Types: string, number, boolean","de":"Grundtypen: string, number, boolean"}'::jsonb,
  '[{"step":1,"text":{"en":"The three most common basic types are string, number, and boolean — matching the three basic kinds of value you already write in plain JavaScript every day.","de":"Die drei häufigsten Grundtypen sind string, number und boolean — sie entsprechen den drei grundlegenden Wertarten, die du schon täglich in reinem JavaScript schreibst."}},{"step":2,"text":{"en":"Function parameters can be typed too: (name: string, age: number). TypeScript refuses to compile if you try to call the function with the wrong kind of value.","de":"Auch Funktionsparameter können typisiert werden: (name: string, age: number). TypeScript verweigert die Kompilierung, wenn du versuchst, die Funktion mit der falschen Art von Wert aufzurufen."}},{"step":3,"text":{"en":"The \": string\" right after the closing parenthesis describes the function''s return type — a promise about what kind of value it hands back to whoever calls it.","de":"Das \": string\" direkt nach der schließenden Klammer beschreibt den Rückgabetyp der Funktion — ein Versprechen, welche Art von Wert sie an den Aufrufer zurückgibt."}}]'::jsonb,
  '{"ts":"let age: number = 25;\nlet studentName: string = \"Ahmed\";\nlet isStudent: boolean = true;\n\nfunction describe(name: string, age: number): string {\n  return name + \" is \" + age + \" years old\";\n}\n\nconsole.log(describe(studentName, age));\nconsole.log(isStudent);\n"}'::jsonb,
  'beginner', false, false,
  46
where not exists (select 1 from lessons where slug = 'ts-basic-types');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'ts-basic-types'),
  '{"en":"In `function add(a: number, b: number): number`, what does the final `: number` describe?","de":"Was beschreibt das letzte `: number` in `function add(a: number, b: number): number`?"}'::jsonb,
  '{"en":["A parameter","The return type of the function","A comment","A variable name"],"de":["Einen Parameter","Den Rückgabetyp der Funktion","Einen Kommentar","Einen Variablennamen"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'ts-basic-types')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'ts-interfaces',
  '{"en":"Interfaces: Describing Object Shapes","de":"Interfaces: Die Form von Objekten beschreiben"}'::jsonb,
  '[{"step":1,"text":{"en":"Real code deals with objects, not just single values. An interface describes the exact shape an object must have — which properties it needs, and what type each one is.","de":"Echter Code arbeitet mit Objekten, nicht nur mit einzelnen Werten. Ein Interface beschreibt die genaue Form, die ein Objekt haben muss — welche Eigenschaften es braucht und welchen Typ jede davon hat."}},{"step":2,"text":{"en":"Once a variable is typed as User, TypeScript checks every place it''s used — passing an object with the wrong shape, or a missing property, is caught immediately.","de":"Sobald eine Variable als User typisiert ist, prüft TypeScript jede Stelle, an der sie verwendet wird — ein Objekt mit falscher Form oder einer fehlenden Eigenschaft wird sofort erkannt."}},{"step":3,"text":{"en":"Interfaces don''t exist at runtime at all — they''re a compile-time-only tool, purely for catching mistakes while you write the code, and disappear completely once Babel strips them.","de":"Interfaces existieren zur Laufzeit überhaupt nicht — sie sind ein reines Compile-Zeit-Werkzeug, nur um Fehler beim Schreiben des Codes zu erkennen, und verschwinden vollständig, sobald Babel sie entfernt."}}]'::jsonb,
  '{"ts":"interface User {\n  name: string;\n  age: number;\n  isPremium: boolean;\n}\n\nfunction greetUser(user: User): string {\n  return \"Welcome, \" + user.name + \"!\";\n}\n\nconst student: User = { name: \"Sara\", age: 22, isPremium: false };\nconsole.log(greetUser(student));\n"}'::jsonb,
  'intermediate', false, false,
  47
where not exists (select 1 from lessons where slug = 'ts-interfaces');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'ts-interfaces'),
  '{"en":"What does an interface describe in TypeScript?","de":"Was beschreibt ein Interface in TypeScript?"}'::jsonb,
  '{"en":["The exact shape (properties and types) an object must have","A CSS layout","A database table","How fast a function runs"],"de":["Die genaue Form (Eigenschaften und Typen), die ein Objekt haben muss","Ein CSS-Layout","Eine Datenbanktabelle","Wie schnell eine Funktion läuft"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'ts-interfaces')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'ts-arrays-and-optional',
  '{"en":"Typed Arrays and Optional Properties","de":"Typisierte Arrays und optionale Eigenschaften"}'::jsonb,
  '[{"step":1,"text":{"en":"number[] means \"an array where every item is a number\". You can use the same pattern for any type at all, like string[] or User[].","de":"number[] bedeutet \"ein Array, in dem jedes Element eine number ist\". Du kannst dasselbe Muster für jeden beliebigen Typ nutzen, wie string[] oder User[]."}},{"step":2,"text":{"en":"Adding a ? after a property name in an interface makes it optional — some objects can include it, others can leave it out, and TypeScript allows both.","de":"Ein ? nach einem Eigenschaftsnamen in einem Interface macht sie optional — manche Objekte können sie enthalten, andere weglassen, und TypeScript erlaubt beides."}},{"step":3,"text":{"en":"Look at the starter code: some lessons have a quizId and some don''t, and TypeScript is fine with that difference specifically because of the ? on that property.","de":"Sieh dir den Startcode an: Manche Lektionen haben eine quizId, manche nicht, und TypeScript akzeptiert diesen Unterschied genau wegen des ? bei dieser Eigenschaft."}}]'::jsonb,
  '{"ts":"const scores: number[] = [90, 85, 77];\n\ninterface Lesson {\n  title: string;\n  minutes: number;\n  quizId?: string; // the \"?\" makes this property optional\n}\n\nconst lessons: Lesson[] = [\n  { title: \"HTML Basics\", minutes: 6 },\n  { title: \"CSS Grid\", minutes: 6, quizId: \"abc123\" },\n];\n\nconsole.log(scores.reduce((sum, s) => sum + s, 0) / scores.length);\nconsole.log(lessons.map((l) => l.title));\n"}'::jsonb,
  'intermediate', false, false,
  48
where not exists (select 1 from lessons where slug = 'ts-arrays-and-optional');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'ts-arrays-and-optional'),
  '{"en":"What does adding `?` after a property name in an interface mean?","de":"Was bedeutet ein `?` nach einem Eigenschaftsnamen in einem Interface?"}'::jsonb,
  '{"en":["The property is required","The property is optional — it may or may not be present","It marks the property as a boolean","It deletes the property"],"de":["Die Eigenschaft ist erforderlich","Die Eigenschaft ist optional — sie kann vorhanden sein oder nicht","Sie markiert die Eigenschaft als boolean","Sie löscht die Eigenschaft"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'ts-arrays-and-optional')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'ts-typed-react-props',
  '{"en":"Typed React Props","de":"Typisierte React-Props"}'::jsonb,
  '[{"step":1,"text":{"en":"React components take props — and in TypeScript you can describe exactly what props a component expects using an interface, the same way you typed plain objects before.","de":"React-Komponenten erhalten Props — und in TypeScript kannst du mit einem Interface genau beschreiben, welche Props eine Komponente erwartet, genauso wie du vorher einfache Objekte typisiert hast."}},{"step":2,"text":{"en":"function Greeting({ name, streak }: GreetingProps) tells TypeScript, your editor, and anyone else reading the code precisely what this component needs to receive.","de":"function Greeting({ name, streak }: GreetingProps) sagt TypeScript, deinem Editor und jedem, der den Code liest, genau, was diese Komponente empfangen muss."}},{"step":3,"text":{"en":"Imagine passing streak=\"seven\" (a string) instead of a number — a real TypeScript setup would flag that as an error immediately, before the app ever runs, not after a confusing bug shows up.","de":"Stell dir vor, du würdest streak=\"seven\" (einen String) statt einer Zahl übergeben — ein echtes TypeScript-Setup würde das sofort als Fehler markieren, bevor die App überhaupt läuft, statt dass später ein verwirrender Bug auftaucht."}}]'::jsonb,
  '{"jsx":"interface GreetingProps {\n  name: string;\n  streak: number;\n}\n\nfunction Greeting({ name, streak }: GreetingProps) {\n  return (\n    <div>\n      <h1>Hello, {name}!</h1>\n      <p>You''re on a {streak}-day streak.</p>\n    </div>\n  );\n}\n\nReactDOM.createRoot(document.getElementById(''root'')).render(\n  <Greeting name=\"Ahmed\" streak={7} />\n);\n"}'::jsonb,
  'intermediate', false, false,
  49
where not exists (select 1 from lessons where slug = 'ts-typed-react-props');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'ts-typed-react-props'),
  '{"en":"Why type a React component''s props with an interface?","de":"Warum sollte man die Props einer React-Komponente mit einem Interface typisieren?"}'::jsonb,
  '{"en":["It makes the component render faster","It documents and checks exactly what props the component expects","It''s required by React itself","It changes the component''s CSS"],"de":["Es lässt die Komponente schneller rendern","Es dokumentiert und prüft genau, welche Props die Komponente erwartet","React selbst verlangt es","Es ändert das CSS der Komponente"]}'::jsonb,
  1,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'ts-typed-react-props')
);

insert into lessons (course_id, slug, title, content, starter_code, difficulty, is_free, has_assignment, sort_order)
select
  (select id from courses where slug = 'frontend'),
  'ts-final-project',
  '{"en":"Project: A Typed Shopping Cart","de":"Projekt: Ein typisierter Warenkorb"}'::jsonb,
  '[{"step":1,"text":{"en":"Final project: combine everything from this unit — interfaces, typed arrays, and typed functions — into one small typed program.","de":"Abschlussprojekt: Kombiniere alles aus dieser Einheit — Interfaces, typisierte Arrays und typisierte Funktionen — zu einem kleinen typisierten Programm."}},{"step":2,"text":{"en":"A CartItem interface describes each item; cartTotal takes a typed array of them and returns a typed total; formatPrice takes a number and returns a formatted string.","de":"Ein CartItem-Interface beschreibt jedes Element; cartTotal nimmt ein typisiertes Array davon entgegen und gibt eine typisierte Summe zurück; formatPrice nimmt eine Zahl und gibt einen formatierten String zurück."}},{"step":3,"text":{"en":"Add your own typed function, applyDiscount(total: number, percent: number): number, that returns the discounted total — then submit the finished file to your portfolio.","de":"Füge deine eigene typisierte Funktion applyDiscount(total: number, percent: number): number hinzu, die den rabattierten Gesamtbetrag zurückgibt — und reiche die fertige Datei dann in dein Portfolio ein."}}]'::jsonb,
  '{"ts":"interface CartItem {\n  name: string;\n  price: number;\n  quantity: number;\n}\n\nfunction cartTotal(items: CartItem[]): number {\n  return items.reduce((sum, item) => sum + item.price * item.quantity, 0);\n}\n\nfunction formatPrice(amount: number): string {\n  return \"\\u20ac\" + amount.toFixed(2);\n}\n\nconst cart: CartItem[] = [\n  { name: \"Course access\", price: 4.99, quantity: 1 },\n  { name: \"Certificate\", price: 0, quantity: 1 },\n];\n\nconsole.log(formatPrice(cartTotal(cart)));\n\n// Your task: add a typed function\n// applyDiscount(total: number, percent: number): number\n// that returns the discounted total, and log the result.\n"}'::jsonb,
  'advanced', false, true,
  50
where not exists (select 1 from lessons where slug = 'ts-final-project');

insert into quiz_questions (lesson_id, question, choices, correct_index, sort_order)
select
  (select id from lessons where slug = 'ts-final-project'),
  '{"en":"Which combination does this final project bring together?","de":"Welche Kombination bringt dieses Abschlussprojekt zusammen?"}'::jsonb,
  '{"en":["Interfaces, typed arrays, and typed functions","Only CSS Grid layouts","Only React''s useState hook","Backend routing and middleware"],"de":["Interfaces, typisierte Arrays und typisierte Funktionen","Nur CSS-Grid-Layouts","Nur Reacts useState-Hook","Backend-Routing und Middleware"]}'::jsonb,
  0,
  1
where not exists (
  select 1 from quiz_questions
  where lesson_id = (select id from lessons where slug = 'ts-final-project')
);

